[
  {
    name: "Alexandre Pantoja",
    nickname: "The Cannibal",
    wins: 26,
    losses: 5,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 170.18,
    stance: "Orthodox",
    date_of_birth: "1990-04-16",
    significant_strikes_landed_per_minute: 4.41,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.81,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 1.75,
    takedown_accuracy: 44,
    takedown_defense: 66,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    name: "Brandon Royval",
    nickname: "Raw Dawg",
    wins: 15,
    losses: 6,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Southpaw",
    date_of_birth: "1992-08-16",
    significant_strikes_landed_per_minute: 3.45,
    significant_striking_accuracy: 38,
    significant_strikes_absorbed_per_minute: 2.63,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 0.66,
    takedown_accuracy: 100,
    takedown_defense: 39,
    average_submissions_attempted_per_15_minutes: 2.3,
  },
  {
    name: "Brandon Moreno",
    nickname: "The Assassin Baby",
    wins: 21,
    losses: 7,
    draws: 2,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1993-12-07",
    significant_strikes_landed_per_minute: 3.8,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.4,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 1.73,
    takedown_accuracy: 45,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Amir Albazi",
    nickname: "The Prince",
    wins: 17,
    losses: 1,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1993-10-27",
    significant_strikes_landed_per_minute: 2.8,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 3.07,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 1.71,
    takedown_accuracy: 33,
    takedown_defense: 40,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    name: "Kai Kara-France",
    nickname: "Don't Blink",
    wins: 24,
    losses: 11,
    draws: 0,
    height_cm: 162.56,
    weight_in_kg: 56.7,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1993-03-26",
    significant_strikes_landed_per_minute: 4.57,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 3.24,
    significant_strike_defence: 65,
    average_takedowns_landed_per_15_minutes: 0.63,
    takedown_accuracy: 33,
    takedown_defense: 88,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Matheus Nicolau",
    wins: 19,
    losses: 4,
    draws: 1,
    height_cm: 167.64,
    weight_in_kg: 56.7,
    reach_in_cm: 167.64,
    stance: "Orthodox",
    date_of_birth: "1993-01-06",
    significant_strikes_landed_per_minute: 3.66,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.14,
    significant_strike_defence: 66,
    average_takedowns_landed_per_15_minutes: 1.48,
    takedown_accuracy: 45,
    takedown_defense: 93,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Manel Kape",
    nickname: "StarBoy",
    wins: 19,
    losses: 6,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Southpaw",
    date_of_birth: "1993-11-14",
    significant_strikes_landed_per_minute: 5.12,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 4.51,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.65,
    takedown_accuracy: 37,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Muhammad Mokaev",
    nickname: "The Punisher",
    wins: 11,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "2000-07-30",
    significant_strikes_landed_per_minute: 1.12,
    significant_striking_accuracy: 51,
    significant_strikes_absorbed_per_minute: 1.19,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 6.47,
    takedown_accuracy: 53,
    takedown_defense: 0,
    average_submissions_attempted_per_15_minutes: 1.3,
  },
  {
    name: "Alex Perez",
    wins: 24,
    losses: 7,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 56.7,
    reach_in_cm: 165.1,
    stance: "Orthodox",
    date_of_birth: "1992-03-21",
    significant_strikes_landed_per_minute: 4.67,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.14,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.84,
    takedown_accuracy: 44,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 1.3,
  },
  {
    name: "Tim Elliott",
    wins: 20,
    losses: 13,
    draws: 1,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 167.64,
    stance: "Southpaw",
    date_of_birth: "1986-12-24",
    significant_strikes_landed_per_minute: 3.41,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 2.67,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 3.73,
    takedown_accuracy: 47,
    takedown_defense: 59,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    name: "Steve Erceg",
    nickname: "Astroboy",
    wins: 11,
    losses: 1,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1995-07-27",
    significant_strikes_landed_per_minute: 4.27,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.57,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 2,
    takedown_accuracy: 33,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    name: "Matt Schnell",
    nickname: "Danger",
    wins: 16,
    losses: 7,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1990-01-15",
    significant_strikes_landed_per_minute: 4.24,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 4.46,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0.63,
    takedown_accuracy: 44,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 1.1,
  },
  {
    name: "Tagir Ulanbekov",
    wins: 14,
    losses: 2,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1991-08-07",
    significant_strikes_landed_per_minute: 3.35,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.29,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 3.81,
    takedown_accuracy: 42,
    takedown_defense: 61,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Tatsuro Taira",
    wins: 14,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "2000-01-27",
    significant_strikes_landed_per_minute: 3.23,
    significant_striking_accuracy: 69,
    significant_strikes_absorbed_per_minute: 1.26,
    significant_strike_defence: 47,
    average_takedowns_landed_per_15_minutes: 2.41,
    takedown_accuracy: 41,
    takedown_defense: 60,
    average_submissions_attempted_per_15_minutes: 2.8,
  },
  {
    name: "David Dvorak",
    nickname: "Undertaker",
    wins: 20,
    losses: 6,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1992-06-05",
    significant_strikes_landed_per_minute: 3.48,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.29,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.58,
    takedown_accuracy: 30,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Sumudaerji",
    nickname: "The Tibetan Eagle",
    wins: 16,
    losses: 5,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 56.7,
    reach_in_cm: 182.88,
    stance: "Southpaw",
    date_of_birth: "1996-01-20",
    significant_strikes_landed_per_minute: 4.83,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 2.75,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 0.32,
    takedown_accuracy: 100,
    takedown_defense: 66,
    average_submissions_attempted_per_15_minutes: 0.6,
  },
  {
    name: "Sean O'Malley",
    nickname: "Sugar",
    wins: 17,
    losses: 1,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 61.23,
    reach_in_cm: 182.88,
    stance: "Switch",
    date_of_birth: "1994-10-24",
    significant_strikes_landed_per_minute: 7.25,
    significant_striking_accuracy: 61,
    significant_strikes_absorbed_per_minute: 3.51,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 0.43,
    takedown_accuracy: 42,
    takedown_defense: 62,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Merab Dvalishvili",
    nickname: "The Machine",
    wins: 16,
    losses: 4,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 61.23,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1991-01-10",
    significant_strikes_landed_per_minute: 4.46,
    significant_striking_accuracy: 41,
    significant_strikes_absorbed_per_minute: 2.41,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 6.55,
    takedown_accuracy: 36,
    takedown_defense: 78,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Aljamain Sterling",
    nickname: "Funk Master",
    wins: 23,
    losses: 4,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 61.23,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1989-07-31",
    significant_strikes_landed_per_minute: 4.73,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.41,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.97,
    takedown_accuracy: 24,
    takedown_defense: 45,
    average_submissions_attempted_per_15_minutes: 0.8,
  },
  {
    name: "Cory Sandhagen",
    wins: 17,
    losses: 4,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 61.23,
    reach_in_cm: 177.8,
    stance: "Switch",
    date_of_birth: "1992-04-20",
    significant_strikes_landed_per_minute: 5.33,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.4,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.36,
    takedown_accuracy: 33,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Petr Yan",
    nickname: "No Mercy",
    wins: 16,
    losses: 5,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 61.23,
    reach_in_cm: 170.18,
    stance: "Switch",
    date_of_birth: "1993-02-11",
    significant_strikes_landed_per_minute: 5.03,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 4.26,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 1.71,
    takedown_accuracy: 52,
    takedown_defense: 85,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Marlon Vera",
    nickname: "Chito",
    wins: 21,
    losses: 8,
    draws: 1,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 177.8,
    stance: "Switch",
    date_of_birth: "1992-12-02",
    significant_strikes_landed_per_minute: 4.37,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 5.16,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.58,
    takedown_accuracy: 39,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Henry Cejudo",
    nickname: "Triple C",
    wins: 16,
    losses: 3,
    draws: 0,
    height_cm: 162.56,
    weight_in_kg: 61.23,
    reach_in_cm: 162.56,
    stance: "Orthodox",
    date_of_birth: "1987-02-09",
    significant_strikes_landed_per_minute: 3.93,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 3.15,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.07,
    takedown_accuracy: 34,
    takedown_defense: 83,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Song Yadong",
    nickname: "Kung Fu Kid",
    wins: 20,
    losses: 7,
    draws: 1,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 170.18,
    stance: "Orthodox",
    date_of_birth: "1997-12-02",
    significant_strikes_landed_per_minute: 4.61,
    significant_striking_accuracy: 42,
    significant_strikes_absorbed_per_minute: 3.77,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.53,
    takedown_accuracy: 55,
    takedown_defense: 72,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Deiveson Figueiredo",
    nickname: "Deus da Guerra",
    wins: 22,
    losses: 3,
    draws: 1,
    height_cm: 165.1,
    weight_in_kg: 61.23,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1987-12-18",
    significant_strikes_landed_per_minute: 3.08,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 3.46,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 1.65,
    takedown_accuracy: 44,
    takedown_defense: 58,
    average_submissions_attempted_per_15_minutes: 1.6,
  },
  {
    name: "Rob Font",
    wins: 20,
    losses: 8,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1987-06-25",
    significant_strikes_landed_per_minute: 5.53,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.65,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 0.89,
    takedown_accuracy: 35,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Umar Nurmagomedov",
    wins: 16,
    losses: 0,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1996-01-03",
    significant_strikes_landed_per_minute: 4.85,
    significant_striking_accuracy: 70,
    significant_strikes_absorbed_per_minute: 0.73,
    significant_strike_defence: 75,
    average_takedowns_landed_per_15_minutes: 4.28,
    takedown_accuracy: 45,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Jonathan Martinez",
    nickname: "Dragon",
    wins: 19,
    losses: 4,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1994-04-20",
    significant_strikes_landed_per_minute: 4.64,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 3.76,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 0.44,
    takedown_accuracy: 41,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Dominick Cruz",
    nickname: "The Dominator",
    wins: 24,
    losses: 4,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1985-03-09",
    significant_strikes_landed_per_minute: 3.91,
    significant_striking_accuracy: 33,
    significant_strikes_absorbed_per_minute: 2.61,
    significant_strike_defence: 70,
    average_takedowns_landed_per_15_minutes: 2.82,
    takedown_accuracy: 42,
    takedown_defense: 83,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Pedro Munhoz",
    nickname: "The Young Punisher",
    wins: 20,
    losses: 8,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 61.23,
    reach_in_cm: 165.1,
    stance: "Orthodox",
    date_of_birth: "1986-09-07",
    significant_strikes_landed_per_minute: 5.45,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 6.14,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 0.47,
    takedown_accuracy: 19,
    takedown_defense: 82,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Mario Bautista",
    wins: 13,
    losses: 2,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 61.23,
    reach_in_cm: 175.26,
    stance: "Switch",
    date_of_birth: "1993-07-01",
    significant_strikes_landed_per_minute: 5.32,
    significant_striking_accuracy: 51,
    significant_strikes_absorbed_per_minute: 4.2,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 2.72,
    takedown_accuracy: 50,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 1.3,
  },
  {
    name: "Ricky Simon",
    wins: 20,
    losses: 4,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 61.23,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1992-08-31",
    significant_strikes_landed_per_minute: 3.01,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.23,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 5.84,
    takedown_accuracy: 50,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Ilia Topuria",
    nickname: "El Matador",
    wins: 14,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 65.77,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1997-01-21",
    significant_strikes_landed_per_minute: 4.44,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 3.05,
    significant_strike_defence: 67,
    average_takedowns_landed_per_15_minutes: 2.19,
    takedown_accuracy: 56,
    takedown_defense: 92,
    average_submissions_attempted_per_15_minutes: 1.5,
  },
  {
    name: "Alexander Volkanovski",
    nickname: "The Great",
    wins: 26,
    losses: 3,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1988-09-29",
    significant_strikes_landed_per_minute: 6.19,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3.42,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.84,
    takedown_accuracy: 37,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Max Holloway",
    nickname: "Blessed",
    wins: 25,
    losses: 7,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1991-12-04",
    significant_strikes_landed_per_minute: 7.17,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 4.75,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.27,
    takedown_accuracy: 53,
    takedown_defense: 84,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Brian Ortega",
    nickname: "T-City",
    wins: 15,
    losses: 3,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 65.77,
    reach_in_cm: 175.26,
    stance: "Switch",
    date_of_birth: "1991-02-21",
    significant_strikes_landed_per_minute: 4.19,
    significant_striking_accuracy: 38,
    significant_strikes_absorbed_per_minute: 6.66,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 0.95,
    takedown_accuracy: 23,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    name: "Yair Rodriguez",
    nickname: "El Pantera",
    wins: 16,
    losses: 4,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1992-10-06",
    significant_strikes_landed_per_minute: 4.63,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 4.07,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.73,
    takedown_accuracy: 28,
    takedown_defense: 59,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    name: "Movsar Evloev",
    wins: 17,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 65.77,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1994-02-11",
    significant_strikes_landed_per_minute: 4.57,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 2.74,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 4.71,
    takedown_accuracy: 50,
    takedown_defense: 71,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Arnold Allen",
    nickname: "Almighty",
    wins: 19,
    losses: 2,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 65.77,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1994-01-22",
    significant_strikes_landed_per_minute: 3.34,
    significant_striking_accuracy: 40,
    significant_strikes_absorbed_per_minute: 2.86,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 1.12,
    takedown_accuracy: 50,
    takedown_defense: 76,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Josh Emmett",
    nickname: "CC0",
    wins: 18,
    losses: 4,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 65.77,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1985-03-04",
    significant_strikes_landed_per_minute: 4.07,
    significant_striking_accuracy: 36,
    significant_strikes_absorbed_per_minute: 4.66,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 0.92,
    takedown_accuracy: 37,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Calvin Kattar",
    wins: 23,
    losses: 7,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1988-03-26",
    significant_strikes_landed_per_minute: 5.12,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 7.1,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0.42,
    takedown_accuracy: 29,
    takedown_defense: 91,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Giga Chikadze",
    nickname: "Ninja",
    wins: 15,
    losses: 3,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 65.77,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1988-08-25",
    significant_strikes_landed_per_minute: 4.08,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.44,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 0.23,
    takedown_accuracy: 33,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Bryce Mitchell",
    nickname: "Thug Nasty",
    wins: 16,
    losses: 2,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 65.77,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1994-10-04",
    significant_strikes_landed_per_minute: 2.34,
    significant_striking_accuracy: 58,
    significant_strikes_absorbed_per_minute: 1.64,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 3.51,
    takedown_accuracy: 41,
    takedown_defense: 33,
    average_submissions_attempted_per_15_minutes: 1.6,
  },
  {
    name: "Edson Barboza",
    nickname: "Junior",
    wins: 24,
    losses: 11,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1986-01-21",
    significant_strikes_landed_per_minute: 4.18,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 4.34,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 0.48,
    takedown_accuracy: 50,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Dan Ige",
    nickname: "50K",
    wins: 17,
    losses: 7,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1991-08-06",
    significant_strikes_landed_per_minute: 3.76,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.53,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 1.07,
    takedown_accuracy: 26,
    takedown_defense: 58,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Sodiq Yusuff",
    nickname: "Super",
    wins: 13,
    losses: 3,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1993-05-19",
    significant_strikes_landed_per_minute: 5.72,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 4.33,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0.28,
    takedown_accuracy: 20,
    takedown_defense: 62,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Lerone Murphy",
    nickname: "The Miracle",
    wins: 13,
    losses: 0,
    draws: 1,
    height_cm: 175.26,
    weight_in_kg: 65.77,
    reach_in_cm: 185.42,
    stance: "Orthodox",
    date_of_birth: "1991-07-22",
    significant_strikes_landed_per_minute: 3.65,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.4,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 1.29,
    takedown_accuracy: 46,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Alex Caceres",
    nickname: "Bruce Leeroy",
    wins: 21,
    losses: 14,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 65.77,
    reach_in_cm: 185.42,
    stance: "Southpaw",
    date_of_birth: "1988-06-20",
    significant_strikes_landed_per_minute: 4.16,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.93,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 0.56,
    takedown_accuracy: 68,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    name: "Islam Makhachev",
    wins: 25,
    losses: 1,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1991-10-27",
    significant_strikes_landed_per_minute: 2.46,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 1.27,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 3.17,
    takedown_accuracy: 60,
    takedown_defense: 90,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    name: "Charles Oliveira",
    nickname: "Do Bronxs",
    wins: 34,
    losses: 9,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1989-10-17",
    significant_strikes_landed_per_minute: 3.54,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.19,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 2.32,
    takedown_accuracy: 40,
    takedown_defense: 55,
    average_submissions_attempted_per_15_minutes: 2.7,
  },
  {
    name: "Justin Gaethje",
    nickname: "The Highlight",
    wins: 25,
    losses: 4,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 70.31,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1988-11-14",
    significant_strikes_landed_per_minute: 7.35,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 7.5,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 0.13,
    takedown_accuracy: 25,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Dustin Poirier",
    nickname: "The Diamond",
    wins: 29,
    losses: 8,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Southpaw",
    date_of_birth: "1989-01-19",
    significant_strikes_landed_per_minute: 5.49,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 4.3,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.36,
    takedown_accuracy: 36,
    takedown_defense: 63,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    name: "Arman Tsarukyan",
    nickname: "Ahalkalakets",
    wins: 21,
    losses: 3,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1996-10-11",
    significant_strikes_landed_per_minute: 3.85,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 1.91,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 3.4,
    takedown_accuracy: 36,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Michael Chandler",
    nickname: "Iron",
    wins: 23,
    losses: 8,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 70.31,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1986-04-24",
    significant_strikes_landed_per_minute: 4.89,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 4.58,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 2.17,
    takedown_accuracy: 38,
    takedown_defense: 71,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Mateusz Gamrot",
    nickname: "Gamer",
    wins: 23,
    losses: 2,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1990-12-11",
    significant_strikes_landed_per_minute: 2.97,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 3.17,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 4.36,
    takedown_accuracy: 30,
    takedown_defense: 90,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Beneil Dariush",
    wins: 22,
    losses: 6,
    draws: 1,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Southpaw",
    date_of_birth: "1989-05-06",
    significant_strikes_landed_per_minute: 3.78,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 2.65,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 1.9,
    takedown_accuracy: 34,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Rafael Fiziev",
    nickname: "Ataman",
    wins: 12,
    losses: 3,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 70.31,
    reach_in_cm: 180.34,
    stance: "Switch",
    date_of_birth: "1993-03-05",
    significant_strikes_landed_per_minute: 4.9,
    significant_striking_accuracy: 51,
    significant_strikes_absorbed_per_minute: 4.97,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 0.29,
    takedown_accuracy: 40,
    takedown_defense: 89,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Jalin Turner",
    nickname: "The Tarantula",
    wins: 14,
    losses: 7,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 70.31,
    reach_in_cm: 195.58,
    stance: "Southpaw",
    date_of_birth: "1995-05-18",
    significant_strikes_landed_per_minute: 6.02,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.63,
    significant_strike_defence: 41,
    average_takedowns_landed_per_15_minutes: 0.88,
    takedown_accuracy: 55,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    name: "Dan Hooker",
    nickname: "The Hangman",
    wins: 23,
    losses: 12,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 70.31,
    reach_in_cm: 190.5,
    stance: "Switch",
    date_of_birth: "1990-02-13",
    significant_strikes_landed_per_minute: 5.08,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.76,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.79,
    takedown_accuracy: 34,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Rafael Dos Anjos",
    wins: 32,
    losses: 15,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 77.11,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1984-10-26",
    significant_strikes_landed_per_minute: 3.52,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 3.19,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.01,
    takedown_accuracy: 35,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 0.6,
  },
  {
    name: "Benoit Saint Denis",
    nickname: "God of War",
    wins: 13,
    losses: 1,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 70.31,
    reach_in_cm: 185.42,
    stance: "Southpaw",
    date_of_birth: "1995-12-18",
    significant_strikes_landed_per_minute: 5.53,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 5.2,
    significant_strike_defence: 44,
    average_takedowns_landed_per_15_minutes: 4.55,
    takedown_accuracy: 36,
    takedown_defense: 66,
    average_submissions_attempted_per_15_minutes: 1.4,
  },
  {
    name: "Renato Moicano",
    wins: 17,
    losses: 5,
    draws: 1,
    height_cm: 180.34,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1989-05-21",
    significant_strikes_landed_per_minute: 4.75,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 4.07,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 1.66,
    takedown_accuracy: 46,
    takedown_defense: 74,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    name: "Bobby Green",
    nickname: "King",
    wins: 31,
    losses: 15,
    draws: 1,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1986-09-09",
    significant_strikes_landed_per_minute: 6.14,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 3.74,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 1.2,
    takedown_accuracy: 37,
    takedown_defense: 74,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Drew Dober",
    wins: 27,
    losses: 12,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 70.31,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1988-10-19",
    significant_strikes_landed_per_minute: 4.58,
    significant_striking_accuracy: 40,
    significant_strikes_absorbed_per_minute: 4.46,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.68,
    takedown_accuracy: 17,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Leon Edwards",
    nickname: "Rocky",
    wins: 21,
    losses: 3,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 77.11,
    reach_in_cm: 187.96,
    stance: "Southpaw",
    date_of_birth: "1991-08-25",
    significant_strikes_landed_per_minute: 2.8,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 2.4,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.26,
    takedown_accuracy: 33,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Kamaru Usman",
    nickname: "The Nigerian Nightmare",
    wins: 20,
    losses: 4,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 77.11,
    reach_in_cm: 193.04,
    stance: "Switch",
    date_of_birth: "1987-05-11",
    significant_strikes_landed_per_minute: 4.36,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.74,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 2.82,
    takedown_accuracy: 45,
    takedown_defense: 89,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Belal Muhammad",
    nickname: "Remember the Name",
    wins: 23,
    losses: 3,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1988-07-09",
    significant_strikes_landed_per_minute: 4.55,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.64,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 1.98,
    takedown_accuracy: 35,
    takedown_defense: 93,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Shavkat Rakhmonov",
    nickname: "Nomad",
    wins: 17,
    losses: 0,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 77.11,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1994-10-23",
    significant_strikes_landed_per_minute: 4.45,
    significant_striking_accuracy: 59,
    significant_strikes_absorbed_per_minute: 2.61,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.49,
    takedown_accuracy: 33,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 1.5,
  },
  {
    name: "Gilbert Burns",
    nickname: "Durinho",
    wins: 22,
    losses: 6,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 77.11,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1986-07-20",
    significant_strikes_landed_per_minute: 3.36,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.34,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 1.95,
    takedown_accuracy: 35,
    takedown_defense: 47,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Colby Covington",
    nickname: "Chaos",
    wins: 17,
    losses: 3,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1988-02-22",
    significant_strikes_landed_per_minute: 4.1,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 3.05,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 4.05,
    takedown_accuracy: 45,
    takedown_defense: 72,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Ian Machado Garry",
    nickname: "The Future",
    wins: 13,
    losses: 0,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 77.11,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1997-11-17",
    significant_strikes_landed_per_minute: 6.67,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 3.58,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 0.67,
    takedown_accuracy: 75,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Sean Brady",
    wins: 16,
    losses: 1,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 77.11,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1992-11-23",
    significant_strikes_landed_per_minute: 3.77,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.55,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 3.29,
    takedown_accuracy: 57,
    takedown_defense: 87,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    name: "Stephen Thompson",
    nickname: "Wonderboy",
    wins: 17,
    losses: 6,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1983-02-11",
    significant_strikes_landed_per_minute: 4.2,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.04,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0.27,
    takedown_accuracy: 41,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Geoff Neal",
    nickname: "Handz of Steel",
    wins: 15,
    losses: 5,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1990-08-28",
    significant_strikes_landed_per_minute: 5.22,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 5.6,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 0.51,
    takedown_accuracy: 44,
    takedown_defense: 87,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Vicente Luque",
    nickname: "The Silent Assassin",
    wins: 22,
    losses: 9,
    draws: 1,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1991-11-27",
    significant_strikes_landed_per_minute: 5.17,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 5.15,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 1.04,
    takedown_accuracy: 60,
    takedown_defense: 62,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    name: "Jack Della Maddalena",
    wins: 16,
    losses: 2,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 185.42,
    stance: "Switch",
    date_of_birth: "1996-09-10",
    significant_strikes_landed_per_minute: 7.2,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 4.83,
    significant_strike_defence: 67,
    average_takedowns_landed_per_15_minutes: 0.27,
    takedown_accuracy: 20,
    takedown_defense: 82,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Neil Magny",
    nickname: "The Haitian Sensation",
    wins: 28,
    losses: 12,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 77.11,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1987-08-03",
    significant_strikes_landed_per_minute: 3.45,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 2.4,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 2.22,
    takedown_accuracy: 40,
    takedown_defense: 55,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Kevin Holland",
    nickname: "Trailblazer",
    wins: 25,
    losses: 10,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 77.11,
    reach_in_cm: 205.74,
    stance: "Orthodox",
    date_of_birth: "1992-11-05",
    significant_strikes_landed_per_minute: 4.39,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 3.22,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.78,
    takedown_accuracy: 38,
    takedown_defense: 53,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Michael Chiesa",
    nickname: "Maverick",
    wins: 18,
    losses: 7,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1987-12-07",
    significant_strikes_landed_per_minute: 1.87,
    significant_striking_accuracy: 40,
    significant_strikes_absorbed_per_minute: 1.7,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 3.33,
    takedown_accuracy: 50,
    takedown_defense: 60,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    name: "Rinat Fakhretdinov",
    nickname: "Gladiator",
    wins: 21,
    losses: 1,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 77.11,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1991-09-28",
    significant_strikes_landed_per_minute: 4.05,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 2.16,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 4.25,
    takedown_accuracy: 46,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Dricus Du Plessis",
    nickname: "Stillknocks",
    wins: 20,
    losses: 2,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Switch",
    date_of_birth: "1994-01-14",
    significant_strikes_landed_per_minute: 6.95,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 3.79,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 2.72,
    takedown_accuracy: 50,
    takedown_defense: 40,
    average_submissions_attempted_per_15_minutes: 1.1,
  },
  {
    name: "Sean Strickland",
    wins: 28,
    losses: 5,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1991-02-27",
    significant_strikes_landed_per_minute: 5.82,
    significant_striking_accuracy: 41,
    significant_strikes_absorbed_per_minute: 4.24,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 0.92,
    takedown_accuracy: 64,
    takedown_defense: 84,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Israel Adesanya",
    nickname: "The Last Stylebender",
    wins: 24,
    losses: 3,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 83.91,
    reach_in_cm: 203.2,
    stance: "Switch",
    date_of_birth: "1989-07-22",
    significant_strikes_landed_per_minute: 3.93,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.11,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 0.05,
    takedown_accuracy: 14,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Robert Whittaker",
    nickname: "The Reaper",
    wins: 25,
    losses: 7,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 83.91,
    reach_in_cm: 185.42,
    stance: "Orthodox",
    date_of_birth: "1990-12-20",
    significant_strikes_landed_per_minute: 4.47,
    significant_striking_accuracy: 42,
    significant_strikes_absorbed_per_minute: 3.39,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 0.85,
    takedown_accuracy: 39,
    takedown_defense: 82,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Jared Cannonier",
    nickname: "The Killa Gorilla",
    wins: 17,
    losses: 6,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 83.91,
    reach_in_cm: 195.58,
    stance: "Switch",
    date_of_birth: "1984-03-16",
    significant_strikes_landed_per_minute: 4.68,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 4.13,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.44,
    takedown_accuracy: 42,
    takedown_defense: 63,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Marvin Vettori",
    nickname: "The Italian Dream",
    wins: 19,
    losses: 7,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 83.91,
    reach_in_cm: 187.96,
    stance: "Southpaw",
    date_of_birth: "1993-09-20",
    significant_strikes_landed_per_minute: 4.56,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 4.24,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 1.66,
    takedown_accuracy: 45,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Brendan Allen",
    nickname: "All In",
    wins: 23,
    losses: 5,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1995-12-28",
    significant_strikes_landed_per_minute: 3.87,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 3.6,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 1.36,
    takedown_accuracy: 47,
    takedown_defense: 58,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    name: "Paulo Costa",
    nickname: "The Eraser",
    wins: 14,
    losses: 2,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1991-04-21",
    significant_strikes_landed_per_minute: 6.5,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 6.38,
    significant_strike_defence: 47,
    average_takedowns_landed_per_15_minutes: 0.53,
    takedown_accuracy: 75,
    takedown_defense: 79,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Nassourdine Imavov",
    wins: 12,
    losses: 4,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1995-03-01",
    significant_strikes_landed_per_minute: 4.55,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.76,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.09,
    takedown_accuracy: 31,
    takedown_defense: 72,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    name: "Roman Dolidze",
    wins: 12,
    losses: 2,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1988-07-15",
    significant_strikes_landed_per_minute: 3.02,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.01,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 1.72,
    takedown_accuracy: 50,
    takedown_defense: 33,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    name: "Jack Hermansson",
    nickname: "The Joker",
    wins: 23,
    losses: 8,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1988-06-10",
    significant_strikes_landed_per_minute: 5.13,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.69,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 1.66,
    takedown_accuracy: 29,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Khamzat Chimaev",
    nickname: "Borz",
    wins: 13,
    losses: 0,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1994-05-01",
    significant_strikes_landed_per_minute: 5.72,
    significant_striking_accuracy: 58,
    significant_strikes_absorbed_per_minute: 3.46,
    significant_strike_defence: 42,
    average_takedowns_landed_per_15_minutes: 3.99,
    takedown_accuracy: 46,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 2.7,
  },
  {
    name: "Paul Craig",
    nickname: "Bearjew",
    wins: 17,
    losses: 7,
    draws: 1,
    height_cm: 190.5,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1987-11-27",
    significant_strikes_landed_per_minute: 2.42,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 2.86,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 1.76,
    takedown_accuracy: 22,
    takedown_defense: 37,
    average_submissions_attempted_per_15_minutes: 1.6,
  },
  {
    name: "Anthony Hernandez",
    nickname: "Fluffy",
    wins: 11,
    losses: 2,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1993-10-18",
    significant_strikes_landed_per_minute: 4.33,
    significant_striking_accuracy: 62,
    significant_strikes_absorbed_per_minute: 3.36,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 6.79,
    takedown_accuracy: 57,
    takedown_defense: 63,
    average_submissions_attempted_per_15_minutes: 2.9,
  },
  {
    name: "Chris Curtis",
    nickname: "Action-Man",
    wins: 30,
    losses: 10,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1987-07-15",
    significant_strikes_landed_per_minute: 5.36,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 6.3,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 92,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Caio Borralho",
    nickname: "The Natural",
    wins: 15,
    losses: 1,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1993-01-16",
    significant_strikes_landed_per_minute: 2.73,
    significant_striking_accuracy: 58,
    significant_strikes_absorbed_per_minute: 1.98,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.16,
    takedown_accuracy: 63,
    takedown_defense: 57,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Alex Pereira",
    nickname: "Poatan",
    wins: 9,
    losses: 2,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1987-07-07",
    significant_strikes_landed_per_minute: 5,
    significant_striking_accuracy: 62,
    significant_strikes_absorbed_per_minute: 3.65,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 0.19,
    takedown_accuracy: 100,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Jamahal Hill",
    nickname: "Sweet Dreams",
    wins: 12,
    losses: 1,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Southpaw",
    date_of_birth: "1991-05-19",
    significant_strikes_landed_per_minute: 7.31,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 3.35,
    significant_strike_defence: 47,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 73,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Jiri Prochazka",
    wins: 29,
    losses: 4,
    draws: 1,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1992-10-14",
    significant_strikes_landed_per_minute: 5.31,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 5.17,
    significant_strike_defence: 40,
    average_takedowns_landed_per_15_minutes: 0.61,
    takedown_accuracy: 50,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Magomed Ankalaev",
    wins: 18,
    losses: 1,
    draws: 1,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1992-06-02",
    significant_strikes_landed_per_minute: 3.56,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.2,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.07,
    takedown_accuracy: 31,
    takedown_defense: 86,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Jan Blachowicz",
    wins: 29,
    losses: 10,
    draws: 1,
    height_cm: 187.96,
    weight_in_kg: 92.99,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1983-02-24",
    significant_strikes_landed_per_minute: 3.41,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.91,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.09,
    takedown_accuracy: 50,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Aleksandar Rakic",
    wins: 14,
    losses: 3,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1992-02-06",
    significant_strikes_landed_per_minute: 4.01,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.3,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 0.82,
    takedown_accuracy: 25,
    takedown_defense: 90,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Nikita Krylov",
    nickname: "The Miner",
    wins: 30,
    losses: 9,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1992-03-07",
    significant_strikes_landed_per_minute: 4.38,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 2.47,
    significant_strike_defence: 44,
    average_takedowns_landed_per_15_minutes: 2.29,
    takedown_accuracy: 38,
    takedown_defense: 53,
    average_submissions_attempted_per_15_minutes: 1.4,
  },
  {
    name: "Johnny Walker",
    wins: 21,
    losses: 7,
    draws: 0,
    height_cm: 198.12,
    weight_in_kg: 92.99,
    reach_in_cm: 208.28,
    stance: "Orthodox",
    date_of_birth: "1992-03-30",
    significant_strikes_landed_per_minute: 3.87,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 2.64,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 0.5,
    takedown_accuracy: 100,
    takedown_defense: 57,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    name: "Khalil Rountree Jr.",
    wins: 13,
    losses: 5,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 92.99,
    reach_in_cm: 193.04,
    stance: "Southpaw",
    date_of_birth: "1990-02-26",
    significant_strikes_landed_per_minute: 3.73,
    significant_striking_accuracy: 38,
    significant_strikes_absorbed_per_minute: 4.16,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Volkan Oezdemir",
    nickname: "No Time",
    wins: 19,
    losses: 7,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 92.99,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1989-09-19",
    significant_strikes_landed_per_minute: 4.59,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 3.92,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0.57,
    takedown_accuracy: 33,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Anthony Smith",
    nickname: "Lionheart",
    wins: 37,
    losses: 18,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1988-07-26",
    significant_strikes_landed_per_minute: 3.16,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.45,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 0.52,
    takedown_accuracy: 28,
    takedown_defense: 48,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    name: "Ryan Spann",
    nickname: "Superman",
    wins: 21,
    losses: 9,
    draws: 0,
    height_cm: 195.58,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1991-08-24",
    significant_strikes_landed_per_minute: 3.42,
    significant_striking_accuracy: 40,
    significant_strikes_absorbed_per_minute: 3.91,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 1.29,
    takedown_accuracy: 35,
    takedown_defense: 47,
    average_submissions_attempted_per_15_minutes: 1.5,
  },
  {
    name: "Alonzo Menifield",
    nickname: "Atomic",
    wins: 14,
    losses: 3,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 92.99,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1987-10-18",
    significant_strikes_landed_per_minute: 3.82,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3.09,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 0.62,
    takedown_accuracy: 30,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    name: "Azamat Murzakanov",
    nickname: "The Professional",
    wins: 13,
    losses: 0,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 92.99,
    reach_in_cm: 180.34,
    stance: "Southpaw",
    date_of_birth: "1989-04-12",
    significant_strikes_landed_per_minute: 4.57,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3.12,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 0.75,
    takedown_accuracy: 16,
    takedown_defense: 83,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Dominick Reyes",
    nickname: "The Devastator",
    wins: 12,
    losses: 4,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 195.58,
    stance: "Southpaw",
    date_of_birth: "1989-12-26",
    significant_strikes_landed_per_minute: 4.75,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 3.77,
    significant_strike_defence: 48,
    average_takedowns_landed_per_15_minutes: 0.36,
    takedown_accuracy: 28,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    name: "Vitor Petrino",
    wins: 10,
    losses: 0,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 92.99,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1997-08-28",
    significant_strikes_landed_per_minute: 3.07,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 2.65,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 4.15,
    takedown_accuracy: 70,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    name: "Jon Jones",
    nickname: "Bones",
    wins: 27,
    losses: 1,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 112.49,
    reach_in_cm: 213.36,
    stance: "Orthodox",
    date_of_birth: "1987-07-19",
    significant_strikes_landed_per_minute: 4.29,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 2.22,
    significant_strike_defence: 64,
    average_takedowns_landed_per_15_minutes: 1.93,
    takedown_accuracy: 45,
    takedown_defense: 95,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Tom Aspinall",
    wins: 14,
    losses: 3,
    draws: 0,
    height_cm: 195.58,
    weight_in_kg: 116.12,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1993-04-11",
    significant_strikes_landed_per_minute: 7.72,
    significant_striking_accuracy: 66,
    significant_strikes_absorbed_per_minute: 2.77,
    significant_strike_defence: 66,
    average_takedowns_landed_per_15_minutes: 3.46,
    takedown_accuracy: 100,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    name: "Ciryl Gane",
    nickname: "Bon Gamin",
    wins: 12,
    losses: 2,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 111.13,
    reach_in_cm: 205.74,
    stance: "Orthodox",
    date_of_birth: "1990-04-12",
    significant_strikes_landed_per_minute: 5.49,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 2.19,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 0.58,
    takedown_accuracy: 21,
    takedown_defense: 50,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Sergei Pavlovich",
    wins: 18,
    losses: 2,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 116.57,
    reach_in_cm: 213.36,
    stance: "Southpaw",
    date_of_birth: "1992-05-13",
    significant_strikes_landed_per_minute: 8.21,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.61,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Stipe Miocic",
    wins: 20,
    losses: 4,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 108.86,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1982-08-19",
    significant_strikes_landed_per_minute: 4.82,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.82,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 1.86,
    takedown_accuracy: 34,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Curtis Blaydes",
    nickname: "Razor",
    wins: 17,
    losses: 4,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 120.2,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1991-02-18",
    significant_strikes_landed_per_minute: 3.56,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 1.89,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 5.93,
    takedown_accuracy: 53,
    takedown_defense: 33,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Alexander Volkov",
    nickname: "Drago",
    wins: 37,
    losses: 10,
    draws: 0,
    height_cm: 200.66,
    weight_in_kg: 113.4,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1988-10-24",
    significant_strikes_landed_per_minute: 5.1,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0.49,
    takedown_accuracy: 63,
    takedown_defense: 73,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    name: "Jailton Almeida",
    nickname: "Malhadinho",
    wins: 20,
    losses: 2,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1991-06-26",
    significant_strikes_landed_per_minute: 2.78,
    significant_striking_accuracy: 64,
    significant_strikes_absorbed_per_minute: 0.52,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 5.14,
    takedown_accuracy: 55,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 2.4,
  },
  {
    name: "Serghei Spivac",
    nickname: "Polar Bear",
    wins: 16,
    losses: 4,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 117.93,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1995-01-24",
    significant_strikes_landed_per_minute: 3.54,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 3.79,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 4.56,
    takedown_accuracy: 64,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Tai Tuivasa",
    nickname: "Bam Bam",
    wins: 15,
    losses: 6,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 119.75,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1993-03-16",
    significant_strikes_landed_per_minute: 3.98,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 4.98,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 54,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Marcin Tybura",
    nickname: "Tybur",
    wins: 24,
    losses: 8,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 112.94,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1985-11-09",
    significant_strikes_landed_per_minute: 3.55,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.35,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 1.39,
    takedown_accuracy: 33,
    takedown_defense: 79,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    name: "Derrick Lewis",
    nickname: "The Black Beast",
    wins: 27,
    losses: 12,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 117.93,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1985-02-07",
    significant_strikes_landed_per_minute: 2.43,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.48,
    significant_strike_defence: 40,
    average_takedowns_landed_per_15_minutes: 0.53,
    takedown_accuracy: 26,
    takedown_defense: 53,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Jairzinho Rozenstruik",
    nickname: "Bigi Boy",
    wins: 13,
    losses: 5,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 109.77,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1988-03-17",
    significant_strikes_landed_per_minute: 2.81,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.15,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 73,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    name: "Alexandr Romanov",
    nickname: "King Kong",
    wins: 17,
    losses: 2,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 118.84,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1990-12-11",
    significant_strikes_landed_per_minute: 4.06,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.2,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 4.32,
    takedown_accuracy: 54,
    takedown_defense: 20,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    name: "Marcos Rogerio de Lima",
    nickname: "Pezao",
    wins: 21,
    losses: 10,
    draws: 1,
    height_cm: 185.42,
    weight_in_kg: 114.76,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1985-06-25",
    significant_strikes_landed_per_minute: 3.61,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 2.96,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 1.34,
    takedown_accuracy: 47,
    takedown_defense: 59,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    name: "Rodrigo Nascimento",
    nickname: "Ze Colmeia",
    wins: 11,
    losses: 1,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 111.58,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1992-11-26",
    significant_strikes_landed_per_minute: 4.31,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.76,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 1.2,
    takedown_accuracy: 33,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
];
