// import flyweight
import Amir from "../assets/flyweight/ALBAZI_AMIR.png";
import David from "../assets/flyweight/DVORAK_DAVID.png";
import TIM from "../assets/flyweight/ELLIOTT_TIM.png";
import STEVEN from "../assets/flyweight/ERCEG_STEVEN.png";
import MANEL from "../assets/flyweight/KAPE_MANEL.png";
import KARA from "../assets/flyweight/KARA-FRANCE_KAI.png";
import MOKAEV from "../assets/flyweight/MOKAEV_MUHAMMAD.png";
import MORENO from "../assets/flyweight/MORENO_BRANDON.png";
import NICOLAU from "../assets/flyweight/NICOLAU_MATHEUS.png";
import PANTOJAALEX from "../assets/flyweight/PANTOJA_ALEXANDRE.png";
import PEREZ from "../assets/flyweight/PEREZ_ALEX.png";
import ROYVAL from "../assets/flyweight/ROYVAL_BRANDON.png";
import SCHNELL from "../assets/flyweight/SCHNELL_MATT.png";
import SUMUDAERJI from "../assets/flyweight/SUMUDAERJI.png";
import TAIRA from "../assets/flyweight/TAIRA_TATSURO.png";
import ULANBEKOV from "../assets/flyweight/ULANBEKOV_TAGIR.png";
// import bantam
import BAUTISTA from "../assets/bantamweight/BAUTISTA_MARIO.png";
import CEJUDO from "../assets/bantamweight/CEJUDO_HENRY.png";
import CRUZ from "../assets/bantamweight/CRUZ_DOMINICK.png";
import MERAB from "../assets/bantamweight/DVALISHVILI_MERAB.png";
import FIGUEREDO from "../assets/bantamweight/FIGUEIREDO_DEIVESON.png";
import FONT from "../assets/bantamweight/FONT_ROB.png";
import MARTINEZ from "../assets/bantamweight/MARTINEZ_JONATHAN.png";
import MUNHOZ from "../assets/bantamweight/MUNHOZ_PEDRO.png";
import Nurmagomedov from "../assets/bantamweight/NURMAGOMEDOV_UMAR.png";
import OMALLEY from "../assets/bantamweight/OMALLEY_SEAN.png";
import PHILLIPS from "../assets/bantamweight/PHILLIPS_KYLER.png";
import SANDHAGEN from "../assets/bantamweight/SANDHAGEN_CORY.png";
import SIMON from "../assets/bantamweight/SIMON_RICKY.png";
import VERA from "../assets/bantamweight/VERA_MARLON.png";
import YADONG from "../assets/bantamweight/YADONG_SONG.png";
import YAN from "../assets/bantamweight/YAN_PETR.png";
//import feather
import ALLEN from "../assets/featherweight/ALLEN_ARNOLD.png";
import BARBOZA from "../assets/featherweight/BARBOZA_EDSON.png";
import CHIKADZE from "../assets/featherweight/CHIKADZE_GIGA.png";
import EMMET from "../assets/featherweight/EMMETT_JOSH.png";
import EVLOEV from "../assets/featherweight/EVLOEV_MOVSAR.png";
import HOLLOWAY from "../assets/featherweight/HOLLOWAY_MAX.png";
import IGE from "../assets/featherweight/IGE_DAN.png";
import KATTAR from "../assets/featherweight/KATTAR_CALVIN.png";
import LOPES from "../assets/featherweight/LOPES_DIEGO.png";
import MITCHELL from "../assets/featherweight/MITCHELL_BRYCE.png";
import ORTEGA from "../assets/featherweight/ORTEGA_BRIAN.png";
import RODRIGUEZ from "../assets/featherweight/RODRIGUEZ_YAIR.png";
import STERLING from "../assets/featherweight/STERLING_ALJAMAIN.png";
import TOPURIAILIA from "../assets/featherweight/TOPURIA_ILIA.png";
import VOLK from "../assets/featherweight/VOLKANOVSKI_ALEXANDER.png";
import YUSUFF from "../assets/featherweight/YUSUFF_SODIQ.png";
//import lightweight
import DARIUSH from "../assets/lightweight/DARIUSH_BENEIL.png";
import DOSANJOS from "../assets/lightweight/DOS_ANJOS_RAFAEL.png";
import FIZIEV from "../assets/lightweight/FIZIEV_RAFAEL.png";
import GAETHJE from "../assets/lightweight/GAETHJE_JUSTIN.png";
import GAMROT from "../assets/lightweight/GAMROT_MATEUSZ.png";
import GREEN from "../assets/lightweight/GREEN_BOBBY.png";
import HOOKER from "../assets/lightweight/HOOKER_DAN.png";
import ISLAM from "../assets/lightweight/MAKHACHEV_ISLAM.png";
import MICHAEL from "../assets/lightweight/MICHAEL.png";
import MOICANO from "../assets/lightweight/MOICANO_RENATO.png";
import OLIVEIRA from "../assets/lightweight/OLIVEIRA_CHARLES.png";
import POIRIER from "../assets/lightweight/POIRIER_DUSTIN.png";
import BENOIT from "../assets/lightweight/SAINT_DENIS_BENOIT.png";
import ARMAN from "../assets/lightweight/TSARUKYAN_ARMAN.png";
import TURNER from "../assets/lightweight/TURNER_JALIN.png";
// import welter
import BRADY from "../assets/welterweight/BRADY_SEAN.png";
import BUCKLEY from "../assets/welterweight/BUCKLEY_JOAQUIN.png";
import BURNS from "../assets/welterweight/BURNS_GILBERT.png";
import COLBY from "../assets/welterweight/COVINGTON_COLBY.png";
import DELLA from "../assets/welterweight/DELLA_MADDALENA_JACK.png";
import LEDWARDS from "../assets/welterweight/EDWARDS_LEON.png";
import GARRY from "../assets/welterweight/GARRY_IAN.png";
import HOLLAND from "../assets/welterweight/HOLLAND_KEVIN.png";
import LUQUE from "../assets/welterweight/LUQUE_VICENTE.png";
import MAGNY from "../assets/welterweight/MAGNY_NEIL.png";
import BELAL from "../assets/welterweight/MUHAMMAD_BELAL.png";
import NEAL from "../assets/welterweight/NEAL_GEOFF.png";
import PAGE from "../assets/welterweight/PAGE_MICHAEL.png";
import SHAVKAT from "../assets/welterweight/RAKHMONOV_SHAVKAT.png";
import THOMPSON from "../assets/welterweight/THOMPSON_STEPHEN.png";
import USMAN from "../assets/welterweight/USMAN_KAMARU.png";
//import middle
import ADESANYA from "../assets/middleweight/ADESANYA_ISRAEL.png";
import ARNOLD from "../assets/middleweight/ALLEN_BRENDAN.png";
import CAIO from "../assets/middleweight/BARRALHO_CAIO.png";
import CANNONIER from "../assets/middleweight/CANNONIER_JARED.png";
import CHIMAEV from "../assets/middleweight/CHIMAEV_KHAMZAT.png";
import COSTA from "../assets/middleweight/COSTA_PAULO.png";
import CRAIG from "../assets/middleweight/CRAIG_PAUL.png";
import CURTIS from "../assets/middleweight/CURTIS_CHRIS.png";
import DOLIDZE from "../assets/middleweight/DOLIDZE_ROMAN.png";
import DUPLESSUS from "../assets/middleweight/DU_PLESSUS_DRICUS.png";
import HERMANSSON from "../assets/middleweight/HERMANSSON_JACK.png";
import HERNANDEZ from "../assets/middleweight/HERNANDEZ_ANTHONY.png";
import IMAVOV from "../assets/middleweight/IMAVOV_NASSOURDINE.png";
import STRICKLAND from "../assets/middleweight/STRICKLAND_SEAN.png";
import VETTORI from "../assets/middleweight/VETTORI_MARVIN.png";
import WHITTAKER from "../assets/middleweight/WHITTAKER_ROBERT.png";
//import lightheavy
import Ankalaev from "../assets/lightheavyweight/ANKALAEV_MAGOMED.png";
import Blachowicz from "../assets/lightheavyweight/BLACHOWICZ_JAN.png";
import GUSKOV from "../assets/lightheavyweight/GUSKOV_BOGDAN.png";
import HILL from "../assets/lightheavyweight/HILL_JAMAHAL.png";
import Krylov from "../assets/lightheavyweight/KRYLOV_NIKITA.png";
import Menifield from "../assets/lightheavyweight/MENIFIELD_ALONZO.png";
import Azamat from "../assets/lightheavyweight/MURZAKANOV_AZAMAT.png";
import VOLKAN from "../assets/lightheavyweight/OEZDEMIR_VOLKAN.png";
import ALEXPEREIRA from "../assets/lightheavyweight/PEREIRA_ALEX.png";
import JIRI from "../assets/lightheavyweight/PROCHAZKA_JIRI.png";
import RAKIC from "../assets/lightheavyweight/RAKIC_ALEKSANDAR.png";
import REYES from "../assets/lightheavyweight/REYES_DOMINICK.png";
import KHALIL from "../assets/lightheavyweight/ROUNTREE_KHALIL.png";
import ASMITH from "../assets/lightheavyweight/SMITH_ANTHONY.png";
import SPANN from "../assets/lightheavyweight/SPANN_RYAN.png";
import WALKER from "../assets/lightheavyweight/WALKER_JOHNNY.png";
//import heavy
import ALMEIDA from "../assets/heavyweight/ALMEIDA_JAILTON.png";
import ASPINALL from "../assets/heavyweight/ASPINALL_TOM.png";
import BLAYDES from "../assets/heavyweight/BLAYDES_CURTIS.png";
import GANE from "../assets/heavyweight/GANE_CIRYL.png";
import IMA from "../assets/heavyweight/IMA_MARCOS.png";
import JONESJ from "../assets/heavyweight/JONES_JON.png";
import LEWIS from "../assets/heavyweight/LEWIS_DERRICK.png";
import MIOCIC from "../assets/heavyweight/MIOCIC_STIPE.png";
import RODRIGO from "../assets/heavyweight/NASCIMENTO_RODRIGO.png";
import SERGEI from "../assets/heavyweight/PAVLOVICH_SERGEI.png";
import ROMANOV from "../assets/heavyweight/ROMANOV_ALEXANDR.png";
import ROZENSTRUIK from "../assets/heavyweight/ROZENSTRUIK_JAIRZINHO.png";
import SPIVAC from "../assets/heavyweight/SPIVAC_SERGHEI.png";
import TAI from "../assets/heavyweight/TUIVASA_TAI.png";
import TYBURA from "../assets/heavyweight/TYBURA_MARCIN.png";
import VOLKOV from "../assets/heavyweight/VOLKOV_ALEXANDER.png";

const fighterStat = [
  {
    id: 1,
    name: "Alexandre Pantoja",
    weightclass: "Flyweight",
    nickname: "The Cannibal",
    img: PANTOJAALEX,
    wins: 26,
    losses: 5,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 170.18,
    stance: "Orthodox",
    date_of_birth: "1990-04-16",
    significant_strikes_landed_per_minute: 4.41,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.81,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 1.75,
    takedown_accuracy: 44,
    takedown_defense: 66,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    id: 2,
    name: "Brandon Royval",
    weightclass: "Flyweight",
    nickname: "Raw Dawg",
    img: ROYVAL,
    wins: 15,
    losses: 6,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Southpaw",
    date_of_birth: "1992-08-16",
    significant_strikes_landed_per_minute: 3.45,
    significant_striking_accuracy: 38,
    significant_strikes_absorbed_per_minute: 2.63,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 0.66,
    takedown_accuracy: 100,
    takedown_defense: 39,
    average_submissions_attempted_per_15_minutes: 2.3,
  },
  {
    id: 3,
    name: "Brandon Moreno",
    weightclass: "Flyweight",
    nickname: "The Assassin Baby",
    img: MORENO,
    wins: 21,
    losses: 7,
    draws: 2,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1993-12-07",
    significant_strikes_landed_per_minute: 3.8,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.4,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 1.73,
    takedown_accuracy: 45,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 4,
    name: "Amir Albazi",
    weightclass: "Flyweight",
    nickname: "The Prince",
    img: Amir,
    wins: 17,
    losses: 1,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1993-10-27",
    significant_strikes_landed_per_minute: 2.8,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 3.07,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 1.71,
    takedown_accuracy: 33,
    takedown_defense: 40,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    id: 5,
    name: "Kai Kara-France",
    weightclass: "Flyweight",
    nickname: "Don't Blink",
    img: KARA,
    wins: 24,
    losses: 11,
    draws: 0,
    height_cm: 162.56,
    weight_in_kg: 56.7,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1993-03-26",
    significant_strikes_landed_per_minute: 4.57,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 3.24,
    significant_strike_defence: 65,
    average_takedowns_landed_per_15_minutes: 0.63,
    takedown_accuracy: 33,
    takedown_defense: 88,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 6,
    name: "Matheus Nicolau",
    weightclass: "Flyweight",
    img: NICOLAU,
    wins: 19,
    losses: 4,
    draws: 1,
    height_cm: 167.64,
    weight_in_kg: 56.7,
    reach_in_cm: 167.64,
    stance: "Orthodox",
    date_of_birth: "1993-01-06",
    significant_strikes_landed_per_minute: 3.66,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.14,
    significant_strike_defence: 66,
    average_takedowns_landed_per_15_minutes: 1.48,
    takedown_accuracy: 45,
    takedown_defense: 93,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 7,
    name: "Manel Kape",
    weightclass: "Flyweight",
    nickname: "StarBoy",
    img: MANEL,
    wins: 19,
    losses: 6,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Southpaw",
    date_of_birth: "1993-11-14",
    significant_strikes_landed_per_minute: 5.12,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 4.51,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.65,
    takedown_accuracy: 37,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 8,
    name: "Muhammad Mokaev",
    weightclass: "Flyweight",
    nickname: "The Punisher",
    img: MOKAEV,
    wins: 11,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "2000-07-30",
    significant_strikes_landed_per_minute: 1.12,
    significant_striking_accuracy: 51,
    significant_strikes_absorbed_per_minute: 1.19,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 6.47,
    takedown_accuracy: 53,
    takedown_defense: 0,
    average_submissions_attempted_per_15_minutes: 1.3,
  },
  {
    id: 9,
    name: "Alex Perez",
    weightclass: "Flyweight",
    img: PEREZ,
    wins: 24,
    losses: 7,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 56.7,
    reach_in_cm: 165.1,
    stance: "Orthodox",
    date_of_birth: "1992-03-21",
    significant_strikes_landed_per_minute: 4.67,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.14,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.84,
    takedown_accuracy: 44,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 1.3,
  },
  {
    id: 10,
    name: "Tim Elliott",
    weightclass: "Flyweight",
    img: TIM,
    wins: 20,
    losses: 13,
    draws: 1,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 167.64,
    stance: "Southpaw",
    date_of_birth: "1986-12-24",
    significant_strikes_landed_per_minute: 3.41,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 2.67,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 3.73,
    takedown_accuracy: 47,
    takedown_defense: 59,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    id: 11,
    name: "Steve Erceg",
    weightclass: "Flyweight",
    nickname: "Astroboy",
    img: STEVEN,
    wins: 11,
    losses: 1,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1995-07-27",
    significant_strikes_landed_per_minute: 4.27,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.57,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 2,
    takedown_accuracy: 33,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    id: 12,
    name: "Matt Schnell",
    weightclass: "Flyweight",
    nickname: "Danger",
    img: SCHNELL,
    wins: 16,
    losses: 7,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1990-01-15",
    significant_strikes_landed_per_minute: 4.24,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 4.46,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0.63,
    takedown_accuracy: 44,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 1.1,
  },
  {
    id: 13,
    name: "Tagir Ulanbekov",
    weightclass: "Flyweight",
    img: ULANBEKOV,
    wins: 14,
    losses: 2,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1991-08-07",
    significant_strikes_landed_per_minute: 3.35,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.29,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 3.81,
    takedown_accuracy: 42,
    takedown_defense: 61,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 14,
    name: "Tatsuro Taira",
    weightclass: "Flyweight",
    img: TAIRA,
    wins: 14,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 56.7,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "2000-01-27",
    significant_strikes_landed_per_minute: 3.23,
    significant_striking_accuracy: 69,
    significant_strikes_absorbed_per_minute: 1.26,
    significant_strike_defence: 47,
    average_takedowns_landed_per_15_minutes: 2.41,
    takedown_accuracy: 41,
    takedown_defense: 60,
    average_submissions_attempted_per_15_minutes: 2.8,
  },
  {
    id: 15,
    name: "David Dvorak",
    weightclass: "Flyweight",
    nickname: "Undertaker",
    img: David,
    wins: 20,
    losses: 6,
    draws: 0,
    height_cm: 165.1,
    weight_in_kg: 56.7,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1992-06-05",
    significant_strikes_landed_per_minute: 3.48,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.29,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.58,
    takedown_accuracy: 30,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 16,
    name: "Sumudaerji",
    weightclass: "Flyweight",
    nickname: "The Tibetan Eagle",
    img: SUMUDAERJI,
    wins: 16,
    losses: 5,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 56.7,
    reach_in_cm: 182.88,
    stance: "Southpaw",
    date_of_birth: "1996-01-20",
    significant_strikes_landed_per_minute: 4.83,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 2.75,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 0.32,
    takedown_accuracy: 100,
    takedown_defense: 66,
    average_submissions_attempted_per_15_minutes: 0.6,
  },
  {
    id: 17,
    name: "Sean O'Malley",
    weightclass: "Bantamweight",
    nickname: "Sugar",
    img: OMALLEY,
    wins: 17,
    losses: 1,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 61.23,
    reach_in_cm: 182.88,
    stance: "Switch",
    date_of_birth: "1994-10-24",
    significant_strikes_landed_per_minute: 7.25,
    significant_striking_accuracy: 61,
    significant_strikes_absorbed_per_minute: 3.51,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 0.43,
    takedown_accuracy: 42,
    takedown_defense: 62,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 18,
    name: "Merab Dvalishvili",
    weightclass: "Bantamweight",
    nickname: "The Machine",
    img: MERAB,
    wins: 16,
    losses: 4,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 61.23,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1991-01-10",
    significant_strikes_landed_per_minute: 4.46,
    significant_striking_accuracy: 41,
    significant_strikes_absorbed_per_minute: 2.41,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 6.55,
    takedown_accuracy: 36,
    takedown_defense: 78,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 19,
    name: "Aljamain Sterling",
    weightclass: "Bantamweight",
    nickname: "Funk Master",
    img: STERLING,
    wins: 23,
    losses: 4,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 61.23,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1989-07-31",
    significant_strikes_landed_per_minute: 4.73,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.41,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.97,
    takedown_accuracy: 24,
    takedown_defense: 45,
    average_submissions_attempted_per_15_minutes: 0.8,
  },
  {
    id: 20,
    name: "Cory Sandhagen",
    weightclass: "Bantamweight",
    img: SANDHAGEN,
    wins: 17,
    losses: 4,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 61.23,
    reach_in_cm: 177.8,
    stance: "Switch",
    date_of_birth: "1992-04-20",
    significant_strikes_landed_per_minute: 5.33,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.4,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.36,
    takedown_accuracy: 33,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 21,
    name: "Petr Yan",
    weightclass: "Bantamweight",
    nickname: "No Mercy",
    img: YAN,
    wins: 16,
    losses: 5,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 61.23,
    reach_in_cm: 170.18,
    stance: "Switch",
    date_of_birth: "1993-02-11",
    significant_strikes_landed_per_minute: 5.03,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 4.26,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 1.71,
    takedown_accuracy: 52,
    takedown_defense: 85,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 23,
    name: "Marlon Vera",
    weightclass: "Bantamweight",
    nickname: "Chito",
    img: VERA,
    wins: 21,
    losses: 8,
    draws: 1,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 177.8,
    stance: "Switch",
    date_of_birth: "1992-12-02",
    significant_strikes_landed_per_minute: 4.37,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 5.16,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.58,
    takedown_accuracy: 39,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 24,
    name: "Henry Cejudo",
    weightclass: "Bantamweight",
    nickname: "Triple C",
    img: CEJUDO,
    wins: 16,
    losses: 3,
    draws: 0,
    height_cm: 162.56,
    weight_in_kg: 61.23,
    reach_in_cm: 162.56,
    stance: "Orthodox",
    date_of_birth: "1987-02-09",
    significant_strikes_landed_per_minute: 3.93,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 3.15,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.07,
    takedown_accuracy: 34,
    takedown_defense: 83,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 25,
    name: "Song Yadong",
    weightclass: "Bantamweight",
    nickname: "Kung Fu Kid",
    img: YADONG,
    wins: 20,
    losses: 7,
    draws: 1,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 170.18,
    stance: "Orthodox",
    date_of_birth: "1997-12-02",
    significant_strikes_landed_per_minute: 4.61,
    significant_striking_accuracy: 42,
    significant_strikes_absorbed_per_minute: 3.77,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.53,
    takedown_accuracy: 55,
    takedown_defense: 72,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 26,
    name: "Deiveson Figueiredo",
    weightclass: "Bantamweight",
    nickname: "Deus da Guerra",
    img: FIGUEREDO,
    wins: 22,
    losses: 3,
    draws: 1,
    height_cm: 165.1,
    weight_in_kg: 61.23,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1987-12-18",
    significant_strikes_landed_per_minute: 3.08,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 3.46,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 1.65,
    takedown_accuracy: 44,
    takedown_defense: 58,
    average_submissions_attempted_per_15_minutes: 1.6,
  },
  {
    id: 27,
    name: "Rob Font",
    weightclass: "Bantamweight",
    img: FONT,
    wins: 20,
    losses: 8,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1987-06-25",
    significant_strikes_landed_per_minute: 5.53,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.65,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 0.89,
    takedown_accuracy: 35,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 28,
    name: "Umar Nurmagomedov",
    weightclass: "Bantamweight",
    img: Nurmagomedov,
    wins: 16,
    losses: 0,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1996-01-03",
    significant_strikes_landed_per_minute: 4.85,
    significant_striking_accuracy: 70,
    significant_strikes_absorbed_per_minute: 0.73,
    significant_strike_defence: 75,
    average_takedowns_landed_per_15_minutes: 4.28,
    takedown_accuracy: 45,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 29,
    name: "Jonathan Martinez",
    weightclass: "Bantamweight",
    nickname: "Dragon",
    img: MARTINEZ,
    wins: 19,
    losses: 4,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1994-04-20",
    significant_strikes_landed_per_minute: 4.64,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 3.76,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 0.44,
    takedown_accuracy: 41,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 30,
    name: "Dominick Cruz",
    weightclass: "Bantamweight",
    nickname: "The Dominator",
    img: CRUZ,
    wins: 24,
    losses: 4,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 61.23,
    reach_in_cm: 172.72,
    stance: "Orthodox",
    date_of_birth: "1985-03-09",
    significant_strikes_landed_per_minute: 3.91,
    significant_striking_accuracy: 33,
    significant_strikes_absorbed_per_minute: 2.61,
    significant_strike_defence: 70,
    average_takedowns_landed_per_15_minutes: 2.82,
    takedown_accuracy: 42,
    takedown_defense: 83,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 31,
    name: "Pedro Munhoz",
    weightclass: "Bantamweight",
    nickname: "The Young Punisher",
    img: MUNHOZ,
    wins: 20,
    losses: 8,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 61.23,
    reach_in_cm: 165.1,
    stance: "Orthodox",
    date_of_birth: "1986-09-07",
    significant_strikes_landed_per_minute: 5.45,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 6.14,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 0.47,
    takedown_accuracy: 19,
    takedown_defense: 82,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 32,
    name: "Mario Bautista",
    weightclass: "Bantamweight",
    img: BAUTISTA,
    wins: 13,
    losses: 2,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 61.23,
    reach_in_cm: 175.26,
    stance: "Switch",
    date_of_birth: "1993-07-01",
    significant_strikes_landed_per_minute: 5.32,
    significant_striking_accuracy: 51,
    significant_strikes_absorbed_per_minute: 4.2,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 2.72,
    takedown_accuracy: 50,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 1.3,
  },
  {
    id: 33,
    name: "Ricky Simon",
    weightclass: "Bantamweight",
    img: SIMON,
    wins: 20,
    losses: 4,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 61.23,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1992-08-31",
    significant_strikes_landed_per_minute: 3.01,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.23,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 5.84,
    takedown_accuracy: 50,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 34,
    name: "Ilia Topuria",
    weightclass: "Featherweight",
    nickname: "El Matador",
    img: TOPURIAILIA,
    wins: 14,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 65.77,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1997-01-21",
    significant_strikes_landed_per_minute: 4.44,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 3.05,
    significant_strike_defence: 67,
    average_takedowns_landed_per_15_minutes: 2.19,
    takedown_accuracy: 56,
    takedown_defense: 92,
    average_submissions_attempted_per_15_minutes: 1.5,
  },
  {
    id: 35,
    name: "Alexander Volkanovski",
    weightclass: "Featherweight",
    nickname: "The Great",
    img: VOLK,
    wins: 26,
    losses: 3,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1988-09-29",
    significant_strikes_landed_per_minute: 6.19,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3.42,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.84,
    takedown_accuracy: 37,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 36,
    name: "Max Holloway",
    weightclass: "Featherweight",
    nickname: "Blessed",
    img: HOLLOWAY,
    wins: 25,
    losses: 7,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 175.26,
    stance: "Orthodox",
    date_of_birth: "1991-12-04",
    significant_strikes_landed_per_minute: 7.17,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 4.75,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.27,
    takedown_accuracy: 53,
    takedown_defense: 84,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 37,
    name: "Brian Ortega",
    weightclass: "Featherweight",
    nickname: "T-City",
    img: ORTEGA,
    wins: 15,
    losses: 3,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 65.77,
    reach_in_cm: 175.26,
    stance: "Switch",
    date_of_birth: "1991-02-21",
    significant_strikes_landed_per_minute: 4.19,
    significant_striking_accuracy: 38,
    significant_strikes_absorbed_per_minute: 6.66,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 0.95,
    takedown_accuracy: 23,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    id: 38,
    name: "Yair Rodriguez",
    weightclass: "Featherweight",
    nickname: "El Pantera",
    img: RODRIGUEZ,
    wins: 16,
    losses: 4,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1992-10-06",
    significant_strikes_landed_per_minute: 4.63,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 4.07,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.73,
    takedown_accuracy: 28,
    takedown_defense: 59,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    id: 39,
    name: "Movsar Evloev",
    weightclass: "Featherweight",
    img: EVLOEV,
    wins: 17,
    losses: 0,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 65.77,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1994-02-11",
    significant_strikes_landed_per_minute: 4.57,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 2.74,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 4.71,
    takedown_accuracy: 50,
    takedown_defense: 71,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 40,
    name: "Arnold Allen",
    weightclass: "Featherweight",
    nickname: "Almighty",
    img: ALLEN,
    wins: 19,
    losses: 2,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 65.77,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1994-01-22",
    significant_strikes_landed_per_minute: 3.34,
    significant_striking_accuracy: 40,
    significant_strikes_absorbed_per_minute: 2.86,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 1.12,
    takedown_accuracy: 50,
    takedown_defense: 76,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 41,
    name: "Josh Emmett",
    weightclass: "Featherweight",
    nickname: "CC0",
    img: EMMET,
    wins: 18,
    losses: 4,
    draws: 0,
    height_cm: 167.64,
    weight_in_kg: 65.77,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1985-03-04",
    significant_strikes_landed_per_minute: 4.07,
    significant_striking_accuracy: 36,
    significant_strikes_absorbed_per_minute: 4.66,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 0.92,
    takedown_accuracy: 37,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 42,
    name: "Calvin Kattar",
    weightclass: "Featherweight",
    img: KATTAR,
    wins: 23,
    losses: 7,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1988-03-26",
    significant_strikes_landed_per_minute: 5.12,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 7.1,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0.42,
    takedown_accuracy: 29,
    takedown_defense: 91,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 43,
    name: "Giga Chikadze",
    weightclass: "Featherweight",
    nickname: "Ninja",
    img: CHIKADZE,
    wins: 15,
    losses: 3,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 65.77,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1988-08-25",
    significant_strikes_landed_per_minute: 4.08,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.44,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 0.23,
    takedown_accuracy: 33,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 44,
    name: "Bryce Mitchell",
    weightclass: "Featherweight",
    nickname: "Thug Nasty",
    img: MITCHELL,
    wins: 16,
    losses: 2,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 65.77,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1994-10-04",
    significant_strikes_landed_per_minute: 2.34,
    significant_striking_accuracy: 58,
    significant_strikes_absorbed_per_minute: 1.64,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 3.51,
    takedown_accuracy: 41,
    takedown_defense: 33,
    average_submissions_attempted_per_15_minutes: 1.6,
  },
  {
    id: 45,
    name: "Edson Barboza",
    weightclass: "Featherweight",
    nickname: "Junior",
    img: BARBOZA,
    wins: 24,
    losses: 11,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 65.77,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1986-01-21",
    significant_strikes_landed_per_minute: 4.18,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 4.34,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 0.48,
    takedown_accuracy: 50,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 46,
    name: "Dan Ige",
    weightclass: "Featherweight",
    nickname: "50K",
    img: IGE,
    wins: 17,
    losses: 7,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1991-08-06",
    significant_strikes_landed_per_minute: 3.76,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.53,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 1.07,
    takedown_accuracy: 26,
    takedown_defense: 58,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 47,
    name: "Sodiq Yusuff",
    weightclass: "Featherweight",
    nickname: "Super",
    img: YUSUFF,
    wins: 13,
    losses: 3,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 65.77,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1993-05-19",
    significant_strikes_landed_per_minute: 5.72,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 4.33,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0.28,
    takedown_accuracy: 20,
    takedown_defense: 62,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 48,
    name: "Lerone Murphy",
    weightclass: "Featherweight",
    nickname: "The Miracle",
    img: PHILLIPS,
    wins: 13,
    losses: 0,
    draws: 1,
    height_cm: 175.26,
    weight_in_kg: 65.77,
    reach_in_cm: 185.42,
    stance: "Orthodox",
    date_of_birth: "1991-07-22",
    significant_strikes_landed_per_minute: 3.65,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.4,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 1.29,
    takedown_accuracy: 46,
    takedown_defense: 46,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 49,
    name: "Alex Caceres",
    weightclass: "Featherweight",
    nickname: "Bruce Leeroy",
    img: LOPES,
    wins: 21,
    losses: 14,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 65.77,
    reach_in_cm: 185.42,
    stance: "Southpaw",
    date_of_birth: "1988-06-20",
    significant_strikes_landed_per_minute: 4.16,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.93,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 0.56,
    takedown_accuracy: 68,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    id: 50,
    name: "Islam Makhachev",
    weightclass: "Lightweight",
    img: ISLAM,
    wins: 25,
    losses: 1,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1991-10-27",
    significant_strikes_landed_per_minute: 2.46,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 1.27,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 3.17,
    takedown_accuracy: 60,
    takedown_defense: 90,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    id: 51,
    name: "Charles Oliveira",
    weightclass: "Lightweight",
    nickname: "Do Bronxs",
    img: OLIVEIRA,
    wins: 34,
    losses: 9,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1989-10-17",
    significant_strikes_landed_per_minute: 3.54,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.19,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 2.32,
    takedown_accuracy: 40,
    takedown_defense: 55,
    average_submissions_attempted_per_15_minutes: 2.7,
  },
  {
    id: 52,
    name: "Justin Gaethje",
    weightclass: "Lightweight",
    nickname: "The Highlight",
    img: GAETHJE,
    wins: 25,
    losses: 4,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 70.31,
    reach_in_cm: 177.8,
    stance: "Orthodox",
    date_of_birth: "1988-11-14",
    significant_strikes_landed_per_minute: 7.35,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 7.5,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 0.13,
    takedown_accuracy: 25,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 53,
    name: "Dustin Poirier",
    weightclass: "Lightweight",
    nickname: "The Diamond",
    img: POIRIER,
    wins: 29,
    losses: 8,
    draws: 0,
    height_cm: 175.26,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Southpaw",
    date_of_birth: "1989-01-19",
    significant_strikes_landed_per_minute: 5.49,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 4.3,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.36,
    takedown_accuracy: 36,
    takedown_defense: 63,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    id: 54,
    name: "Arman Tsarukyan",
    weightclass: "Lightweight",
    nickname: "Ahalkalakets",
    img: ARMAN,
    wins: 21,
    losses: 3,
    draws: 0,
    height_cm: 170.18,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1996-10-11",
    significant_strikes_landed_per_minute: 3.85,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 1.91,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 3.4,
    takedown_accuracy: 36,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 55,
    name: "Michael Chandler",
    weightclass: "Lightweight",
    nickname: "Iron",
    img: MICHAEL,
    wins: 23,
    losses: 8,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 70.31,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1986-04-24",
    significant_strikes_landed_per_minute: 4.89,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 4.58,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 2.17,
    takedown_accuracy: 38,
    takedown_defense: 71,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 56,
    name: "Mateusz Gamrot",
    weightclass: "Lightweight",
    nickname: "Gamer",
    img: GAMROT,
    wins: 23,
    losses: 2,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1990-12-11",
    significant_strikes_landed_per_minute: 2.97,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 3.17,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 4.36,
    takedown_accuracy: 30,
    takedown_defense: 90,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 57,
    name: "Beneil Dariush",
    weightclass: "Lightweight",
    img: DARIUSH,
    wins: 22,
    losses: 6,
    draws: 1,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Southpaw",
    date_of_birth: "1989-05-06",
    significant_strikes_landed_per_minute: 3.78,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 2.65,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 1.9,
    takedown_accuracy: 34,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 58,
    name: "Rafael Fiziev",
    weightclass: "Lightweight",
    nickname: "Ataman",
    img: FIZIEV,
    wins: 12,
    losses: 3,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 70.31,
    reach_in_cm: 180.34,
    stance: "Switch",
    date_of_birth: "1993-03-05",
    significant_strikes_landed_per_minute: 4.9,
    significant_striking_accuracy: 51,
    significant_strikes_absorbed_per_minute: 4.97,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 0.29,
    takedown_accuracy: 40,
    takedown_defense: 89,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 59,
    name: "Jalin Turner",
    weightclass: "Lightweight",
    nickname: "The Tarantula",
    img: TURNER,
    wins: 14,
    losses: 7,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 70.31,
    reach_in_cm: 195.58,
    stance: "Southpaw",
    date_of_birth: "1995-05-18",
    significant_strikes_landed_per_minute: 6.02,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.63,
    significant_strike_defence: 41,
    average_takedowns_landed_per_15_minutes: 0.88,
    takedown_accuracy: 55,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    id: 60,
    name: "Dan Hooker",
    weightclass: "Lightweight",
    nickname: "The Hangman",
    img: HOOKER,
    wins: 23,
    losses: 12,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 70.31,
    reach_in_cm: 190.5,
    stance: "Switch",
    date_of_birth: "1990-02-13",
    significant_strikes_landed_per_minute: 5.08,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.76,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.79,
    takedown_accuracy: 34,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 61,
    name: "Rafael Dos Anjos",
    weightclass: "Lightweight",
    img: DOSANJOS,
    wins: 32,
    losses: 15,
    draws: 0,
    height_cm: 172.72,
    weight_in_kg: 77.11,
    reach_in_cm: 177.8,
    stance: "Southpaw",
    date_of_birth: "1984-10-26",
    significant_strikes_landed_per_minute: 3.52,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 3.19,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.01,
    takedown_accuracy: 35,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 0.6,
  },
  {
    id: 62,
    name: "Benoit Saint Denis",
    weightclass: "Lightweight",
    nickname: "God of War",
    img: BENOIT,
    wins: 13,
    losses: 1,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 70.31,
    reach_in_cm: 185.42,
    stance: "Southpaw",
    date_of_birth: "1995-12-18",
    significant_strikes_landed_per_minute: 5.53,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 5.2,
    significant_strike_defence: 44,
    average_takedowns_landed_per_15_minutes: 4.55,
    takedown_accuracy: 36,
    takedown_defense: 66,
    average_submissions_attempted_per_15_minutes: 1.4,
  },
  {
    id: 63,
    name: "Renato Moicano",
    weightclass: "Lightweight",
    img: MOICANO,
    wins: 17,
    losses: 5,
    draws: 1,
    height_cm: 180.34,
    weight_in_kg: 70.31,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1989-05-21",
    significant_strikes_landed_per_minute: 4.75,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 4.07,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 1.66,
    takedown_accuracy: 46,
    takedown_defense: 74,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    id: 64,
    name: "Bobby Green",
    weightclass: "Lightweight",
    nickname: "King",
    img: GREEN,
    wins: 31,
    losses: 15,
    draws: 1,
    height_cm: 177.8,
    weight_in_kg: 70.31,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1986-09-09",
    significant_strikes_landed_per_minute: 6.14,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 3.74,
    significant_strike_defence: 62,
    average_takedowns_landed_per_15_minutes: 1.2,
    takedown_accuracy: 37,
    takedown_defense: 74,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 65,
    name: "Leon Edwards",
    weightclass: "Welterweight",
    nickname: "Rocky",
    img: LEDWARDS,
    wins: 21,
    losses: 3,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 77.11,
    reach_in_cm: 187.96,
    stance: "Southpaw",
    date_of_birth: "1991-08-25",
    significant_strikes_landed_per_minute: 2.8,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 2.4,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.26,
    takedown_accuracy: 33,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 66,
    name: "Kamaru Usman",
    weightclass: "Welterweight",
    nickname: "The Nigerian Nightmare",
    img: USMAN,
    wins: 20,
    losses: 4,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 77.11,
    reach_in_cm: 193.04,
    stance: "Switch",
    date_of_birth: "1987-05-11",
    significant_strikes_landed_per_minute: 4.36,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.74,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 2.82,
    takedown_accuracy: 45,
    takedown_defense: 89,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 67,
    name: "Belal Muhammad",
    weightclass: "Welterweight",
    nickname: "Remember the Name",
    img: BELAL,
    wins: 23,
    losses: 3,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1988-07-09",
    significant_strikes_landed_per_minute: 4.55,
    significant_striking_accuracy: 43,
    significant_strikes_absorbed_per_minute: 3.64,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 1.98,
    takedown_accuracy: 35,
    takedown_defense: 93,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 68,
    name: "Shavkat Rakhmonov",
    weightclass: "Welterweight",
    nickname: "Nomad",
    img: SHAVKAT,
    wins: 17,
    losses: 0,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 77.11,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1994-10-23",
    significant_strikes_landed_per_minute: 4.45,
    significant_striking_accuracy: 59,
    significant_strikes_absorbed_per_minute: 2.61,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.49,
    takedown_accuracy: 33,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 1.5,
  },
  {
    id: 69,
    name: "Gilbert Burns",
    weightclass: "Welterweight",
    nickname: "Durinho",
    img: BURNS,
    wins: 22,
    losses: 6,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 77.11,
    reach_in_cm: 180.34,
    stance: "Orthodox",
    date_of_birth: "1986-07-20",
    significant_strikes_landed_per_minute: 3.36,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.34,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 1.95,
    takedown_accuracy: 35,
    takedown_defense: 47,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 70,
    name: "Colby Covington",
    weightclass: "Welterweight",
    nickname: "Chaos",
    img: COLBY,
    wins: 17,
    losses: 3,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1988-02-22",
    significant_strikes_landed_per_minute: 4.1,
    significant_striking_accuracy: 39,
    significant_strikes_absorbed_per_minute: 3.05,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 4.05,
    takedown_accuracy: 45,
    takedown_defense: 72,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 71,
    name: "Ian Machado Garry",
    weightclass: "Welterweight",
    nickname: "The Future",
    img: GARRY,
    wins: 13,
    losses: 0,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 77.11,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1997-11-17",
    significant_strikes_landed_per_minute: 6.67,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 3.58,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 0.67,
    takedown_accuracy: 75,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 72,
    name: "Sean Brady",
    weightclass: "Welterweight",
    img: BRADY,
    wins: 16,
    losses: 1,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 77.11,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1992-11-23",
    significant_strikes_landed_per_minute: 3.77,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.55,
    significant_strike_defence: 61,
    average_takedowns_landed_per_15_minutes: 3.29,
    takedown_accuracy: 57,
    takedown_defense: 87,
    average_submissions_attempted_per_15_minutes: 1.2,
  },
  {
    id: 73,
    name: "Stephen Thompson",
    weightclass: "Welterweight",
    nickname: "Wonderboy",
    img: THOMPSON,
    wins: 17,
    losses: 6,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1983-02-11",
    significant_strikes_landed_per_minute: 4.2,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.04,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0.27,
    takedown_accuracy: 41,
    takedown_defense: 64,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 74,
    name: "Geoff Neal",
    weightclass: "Welterweight",
    nickname: "Handz of Steel",
    img: NEAL,
    wins: 15,
    losses: 5,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1990-08-28",
    significant_strikes_landed_per_minute: 5.22,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 5.6,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 0.51,
    takedown_accuracy: 44,
    takedown_defense: 87,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 75,
    name: "Vicente Luque",
    weightclass: "Welterweight",
    nickname: "The Silent Assassin",
    img: LUQUE,
    wins: 22,
    losses: 9,
    draws: 1,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1991-11-27",
    significant_strikes_landed_per_minute: 5.17,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 5.15,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 1.04,
    takedown_accuracy: 60,
    takedown_defense: 62,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    id: 76,
    name: "Jack Della Maddalena",
    weightclass: "Welterweight",
    img: DELLA,
    wins: 16,
    losses: 2,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 77.11,
    reach_in_cm: 185.42,
    stance: "Switch",
    date_of_birth: "1996-09-10",
    significant_strikes_landed_per_minute: 7.2,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 4.83,
    significant_strike_defence: 67,
    average_takedowns_landed_per_15_minutes: 0.27,
    takedown_accuracy: 20,
    takedown_defense: 82,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 77,
    name: "Neil Magny",
    weightclass: "Welterweight",
    nickname: "The Haitian Sensation",
    img: MAGNY,
    wins: 28,
    losses: 12,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 77.11,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1987-08-03",
    significant_strikes_landed_per_minute: 3.45,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 2.4,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 2.22,
    takedown_accuracy: 40,
    takedown_defense: 55,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 78,
    name: "Kevin Holland",
    weightclass: "Welterweight",
    nickname: "Trailblazer",
    img: HOLLAND,
    wins: 25,
    losses: 10,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 77.11,
    reach_in_cm: 205.74,
    stance: "Orthodox",
    date_of_birth: "1992-11-05",
    significant_strikes_landed_per_minute: 4.39,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 3.22,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 0.78,
    takedown_accuracy: 38,
    takedown_defense: 53,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 79,
    name: "Michael Chiesa",
    weightclass: "Welterweight",
    nickname: "Maverick",
    img: PAGE,
    wins: 18,
    losses: 7,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 77.11,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1987-12-07",
    significant_strikes_landed_per_minute: 1.87,
    significant_striking_accuracy: 40,
    significant_strikes_absorbed_per_minute: 1.7,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 3.33,
    takedown_accuracy: 50,
    takedown_defense: 60,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    id: 80,
    name: "Rinat Fakhretdinov",
    weightclass: "Welterweight",
    nickname: "Gladiator",
    img: BUCKLEY,
    wins: 21,
    losses: 1,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 77.11,
    reach_in_cm: 187.96,
    stance: "Orthodox",
    date_of_birth: "1991-09-28",
    significant_strikes_landed_per_minute: 4.05,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 2.16,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 4.25,
    takedown_accuracy: 46,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 81,
    name: "Dricus Du Plessis",
    weightclass: "Middleweight",
    nickname: "Stillknocks",
    img: DUPLESSUS,
    wins: 20,
    losses: 2,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Switch",
    date_of_birth: "1994-01-14",
    significant_strikes_landed_per_minute: 6.95,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 3.79,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 2.72,
    takedown_accuracy: 50,
    takedown_defense: 40,
    average_submissions_attempted_per_15_minutes: 1.1,
  },
  {
    id: 82,
    name: "Sean Strickland",
    weightclass: "Middleweight",
    img: STRICKLAND,
    wins: 28,
    losses: 5,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1991-02-27",
    significant_strikes_landed_per_minute: 5.82,
    significant_striking_accuracy: 41,
    significant_strikes_absorbed_per_minute: 4.24,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 0.92,
    takedown_accuracy: 64,
    takedown_defense: 84,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 83,
    name: "Israel Adesanya",
    weightclass: "Middleweight",
    nickname: "The Last Stylebender",
    img: ADESANYA,
    wins: 24,
    losses: 3,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 83.91,
    reach_in_cm: 203.2,
    stance: "Switch",
    date_of_birth: "1989-07-22",
    significant_strikes_landed_per_minute: 3.93,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.11,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 0.05,
    takedown_accuracy: 14,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 84,
    name: "Robert Whittaker",
    weightclass: "Middleweight",
    nickname: "The Reaper",
    img: WHITTAKER,
    wins: 25,
    losses: 7,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 83.91,
    reach_in_cm: 185.42,
    stance: "Orthodox",
    date_of_birth: "1990-12-20",
    significant_strikes_landed_per_minute: 4.47,
    significant_striking_accuracy: 42,
    significant_strikes_absorbed_per_minute: 3.39,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 0.85,
    takedown_accuracy: 39,
    takedown_defense: 82,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 85,
    name: "Jared Cannonier",
    weightclass: "Middleweight",
    nickname: "The Killa Gorilla",
    img: CANNONIER,
    wins: 17,
    losses: 6,
    draws: 0,
    height_cm: 180.34,
    weight_in_kg: 83.91,
    reach_in_cm: 195.58,
    stance: "Switch",
    date_of_birth: "1984-03-16",
    significant_strikes_landed_per_minute: 4.68,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 4.13,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 0.44,
    takedown_accuracy: 42,
    takedown_defense: 63,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 86,
    name: "Marvin Vettori",
    weightclass: "Middleweight",
    nickname: "The Italian Dream",
    img: VETTORI,
    wins: 19,
    losses: 7,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 83.91,
    reach_in_cm: 187.96,
    stance: "Southpaw",
    date_of_birth: "1993-09-20",
    significant_strikes_landed_per_minute: 4.56,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 4.24,
    significant_strike_defence: 56,
    average_takedowns_landed_per_15_minutes: 1.66,
    takedown_accuracy: 45,
    takedown_defense: 69,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 87,
    name: "Brendan Allen",
    weightclass: "Middleweight",
    nickname: "All In",
    img: ARNOLD,
    wins: 23,
    losses: 5,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1995-12-28",
    significant_strikes_landed_per_minute: 3.87,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 3.6,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 1.36,
    takedown_accuracy: 47,
    takedown_defense: 58,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    id: 88,
    name: "Paulo Costa",
    weightclass: "Middleweight",
    nickname: "The Eraser",
    img: COSTA,
    wins: 14,
    losses: 2,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 182.88,
    stance: "Orthodox",
    date_of_birth: "1991-04-21",
    significant_strikes_landed_per_minute: 6.5,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 6.38,
    significant_strike_defence: 47,
    average_takedowns_landed_per_15_minutes: 0.53,
    takedown_accuracy: 75,
    takedown_defense: 79,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 89,
    name: "Nassourdine Imavov",
    weightclass: "Middleweight",
    img: IMAVOV,
    wins: 12,
    losses: 4,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1995-03-01",
    significant_strikes_landed_per_minute: 4.55,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.76,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.09,
    takedown_accuracy: 31,
    takedown_defense: 72,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    id: 90,
    name: "Roman Dolidze",
    weightclass: "Middleweight",
    img: DOLIDZE,
    wins: 12,
    losses: 2,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1988-07-15",
    significant_strikes_landed_per_minute: 3.02,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.01,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 1.72,
    takedown_accuracy: 50,
    takedown_defense: 33,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    id: 91,
    name: "Jack Hermansson",
    weightclass: "Middleweight",
    nickname: "The Joker",
    img: HERMANSSON,
    wins: 23,
    losses: 8,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 83.91,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1988-06-10",
    significant_strikes_landed_per_minute: 5.13,
    significant_striking_accuracy: 44,
    significant_strikes_absorbed_per_minute: 3.69,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 1.66,
    takedown_accuracy: 29,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 92,
    name: "Khamzat Chimaev",
    weightclass: "Middleweight",
    nickname: "Borz",
    img: CHIMAEV,
    wins: 13,
    losses: 0,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1994-05-01",
    significant_strikes_landed_per_minute: 5.72,
    significant_striking_accuracy: 58,
    significant_strikes_absorbed_per_minute: 3.46,
    significant_strike_defence: 42,
    average_takedowns_landed_per_15_minutes: 3.99,
    takedown_accuracy: 46,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 2.7,
  },
  {
    id: 93,
    name: "Paul Craig",
    weightclass: "Middleweight",
    nickname: "Bearjew",
    img: CRAIG,
    wins: 17,
    losses: 7,
    draws: 1,
    height_cm: 190.5,
    weight_in_kg: 83.91,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1987-11-27",
    significant_strikes_landed_per_minute: 2.42,
    significant_striking_accuracy: 46,
    significant_strikes_absorbed_per_minute: 2.86,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 1.76,
    takedown_accuracy: 22,
    takedown_defense: 37,
    average_submissions_attempted_per_15_minutes: 1.6,
  },
  {
    id: 94,
    name: "Anthony Hernandez",
    weightclass: "Middleweight",
    nickname: "Fluffy",
    img: HERNANDEZ,
    wins: 11,
    losses: 2,
    draws: 0,
    height_cm: 182.88,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1993-10-18",
    significant_strikes_landed_per_minute: 4.33,
    significant_striking_accuracy: 62,
    significant_strikes_absorbed_per_minute: 3.36,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 6.79,
    takedown_accuracy: 57,
    takedown_defense: 63,
    average_submissions_attempted_per_15_minutes: 2.9,
  },
  {
    id: 95,
    name: "Chris Curtis",
    weightclass: "Middleweight",
    nickname: "Action-Man",
    img: CURTIS,
    wins: 30,
    losses: 10,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1987-07-15",
    significant_strikes_landed_per_minute: 5.36,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 6.3,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 92,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 96,
    name: "Caio Borralho",
    weightclass: "Middleweight",
    nickname: "The Natural",
    img: CAIO,
    wins: 15,
    losses: 1,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 83.91,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1993-01-16",
    significant_strikes_landed_per_minute: 2.73,
    significant_striking_accuracy: 58,
    significant_strikes_absorbed_per_minute: 1.98,
    significant_strike_defence: 60,
    average_takedowns_landed_per_15_minutes: 2.16,
    takedown_accuracy: 63,
    takedown_defense: 57,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 97,
    name: "Alex Pereira",
    weightclass: "Light Heavyweight",
    nickname: "Poatan",
    img: ALEXPEREIRA,
    wins: 9,
    losses: 2,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1987-07-07",
    significant_strikes_landed_per_minute: 5,
    significant_striking_accuracy: 62,
    significant_strikes_absorbed_per_minute: 3.65,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 0.19,
    takedown_accuracy: 100,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 98,
    name: "Jamahal Hill",
    weightclass: "Light Heavyweight",
    nickname: "Sweet Dreams",
    img: HILL,
    wins: 12,
    losses: 1,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Southpaw",
    date_of_birth: "1991-05-19",
    significant_strikes_landed_per_minute: 7.31,
    significant_striking_accuracy: 54,
    significant_strikes_absorbed_per_minute: 3.35,
    significant_strike_defence: 47,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 73,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 99,
    name: "Jiri Prochazka",
    weightclass: "Light Heavyweight",
    img: JIRI,
    wins: 29,
    losses: 4,
    draws: 1,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1992-10-14",
    significant_strikes_landed_per_minute: 5.31,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 5.17,
    significant_strike_defence: 40,
    average_takedowns_landed_per_15_minutes: 0.61,
    takedown_accuracy: 50,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 100,
    name: "Magomed Ankalaev",
    weightclass: "Light Heavyweight",
    img: Ankalaev,
    wins: 18,
    losses: 1,
    draws: 1,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1992-06-02",
    significant_strikes_landed_per_minute: 3.56,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.2,
    significant_strike_defence: 58,
    average_takedowns_landed_per_15_minutes: 1.07,
    takedown_accuracy: 31,
    takedown_defense: 86,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 101,
    name: "Jan Blachowicz",
    weightclass: "Light Heavyweight",
    img: Blachowicz,
    wins: 29,
    losses: 10,
    draws: 1,
    height_cm: 187.96,
    weight_in_kg: 92.99,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1983-02-24",
    significant_strikes_landed_per_minute: 3.41,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.91,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 1.09,
    takedown_accuracy: 50,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 102,
    name: "Aleksandar Rakic",
    weightclass: "Light Heavyweight",
    img: RAKIC,
    wins: 14,
    losses: 3,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1992-02-06",
    significant_strikes_landed_per_minute: 4.01,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.3,
    significant_strike_defence: 53,
    average_takedowns_landed_per_15_minutes: 0.82,
    takedown_accuracy: 25,
    takedown_defense: 90,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 103,
    name: "Nikita Krylov",
    weightclass: "Light Heavyweight",
    nickname: "The Miner",
    img: Krylov,
    wins: 30,
    losses: 9,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1992-03-07",
    significant_strikes_landed_per_minute: 4.38,
    significant_striking_accuracy: 55,
    significant_strikes_absorbed_per_minute: 2.47,
    significant_strike_defence: 44,
    average_takedowns_landed_per_15_minutes: 2.29,
    takedown_accuracy: 38,
    takedown_defense: 53,
    average_submissions_attempted_per_15_minutes: 1.4,
  },
  {
    id: 104,
    name: "Johnny Walker",
    weightclass: "Light Heavyweight",
    img: WALKER,
    wins: 21,
    losses: 7,
    draws: 0,
    height_cm: 198.12,
    weight_in_kg: 92.99,
    reach_in_cm: 208.28,
    stance: "Orthodox",
    date_of_birth: "1992-03-30",
    significant_strikes_landed_per_minute: 3.87,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 2.64,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 0.5,
    takedown_accuracy: 100,
    takedown_defense: 57,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    id: 105,
    name: "Khalil Rountree Jr.",
    weightclass: "Light Heavyweight",
    img: KHALIL,
    wins: 13,
    losses: 5,
    draws: 0,
    height_cm: 185.42,
    weight_in_kg: 92.99,
    reach_in_cm: 193.04,
    stance: "Southpaw",
    date_of_birth: "1990-02-26",
    significant_strikes_landed_per_minute: 3.73,
    significant_striking_accuracy: 38,
    significant_strikes_absorbed_per_minute: 4.16,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 56,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 106,
    name: "Volkan Oezdemir",
    weightclass: "Light Heavyweight",
    nickname: "No Time",
    img: VOLKAN,
    wins: 19,
    losses: 7,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 92.99,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1989-09-19",
    significant_strikes_landed_per_minute: 4.59,
    significant_striking_accuracy: 47,
    significant_strikes_absorbed_per_minute: 3.92,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0.57,
    takedown_accuracy: 33,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 107,
    name: "Anthony Smith",
    weightclass: "Light Heavyweight",
    nickname: "Lionheart",
    img: ASMITH,
    wins: 37,
    losses: 18,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1988-07-26",
    significant_strikes_landed_per_minute: 3.16,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.45,
    significant_strike_defence: 46,
    average_takedowns_landed_per_15_minutes: 0.52,
    takedown_accuracy: 28,
    takedown_defense: 48,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
  {
    id: 108,
    name: "Ryan Spann",
    weightclass: "Light Heavyweight",
    nickname: "Superman",
    img: SPANN,
    wins: 21,
    losses: 9,
    draws: 0,
    height_cm: 195.58,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1991-08-24",
    significant_strikes_landed_per_minute: 3.42,
    significant_striking_accuracy: 40,
    significant_strikes_absorbed_per_minute: 3.91,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 1.29,
    takedown_accuracy: 35,
    takedown_defense: 47,
    average_submissions_attempted_per_15_minutes: 1.5,
  },
  {
    id: 109,
    name: "Alonzo Menifield",
    weightclass: "Light Heavyweight",
    nickname: "Atomic",
    img: Menifield,
    wins: 14,
    losses: 3,
    draws: 1,
    height_cm: 182.88,
    weight_in_kg: 92.99,
    reach_in_cm: 193.04,
    stance: "Orthodox",
    date_of_birth: "1987-10-18",
    significant_strikes_landed_per_minute: 3.82,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3.09,
    significant_strike_defence: 52,
    average_takedowns_landed_per_15_minutes: 0.62,
    takedown_accuracy: 30,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0.3,
  },
  {
    id: 110,
    name: "Azamat Murzakanov",
    weightclass: "Light Heavyweight",
    nickname: "The Professional",
    img: Azamat,
    wins: 13,
    losses: 0,
    draws: 0,
    height_cm: 177.8,
    weight_in_kg: 92.99,
    reach_in_cm: 180.34,
    stance: "Southpaw",
    date_of_birth: "1989-04-12",
    significant_strikes_landed_per_minute: 4.57,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3.12,
    significant_strike_defence: 57,
    average_takedowns_landed_per_15_minutes: 0.75,
    takedown_accuracy: 16,
    takedown_defense: 83,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 111,
    name: "Dominick Reyes",
    weightclass: "Light Heavyweight",
    nickname: "The Devastator",
    img: REYES,
    wins: 12,
    losses: 4,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 92.99,
    reach_in_cm: 195.58,
    stance: "Southpaw",
    date_of_birth: "1989-12-26",
    significant_strikes_landed_per_minute: 4.75,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 3.77,
    significant_strike_defence: 48,
    average_takedowns_landed_per_15_minutes: 0.36,
    takedown_accuracy: 28,
    takedown_defense: 80,
    average_submissions_attempted_per_15_minutes: 0.4,
  },
  {
    id: 112,
    name: "Vitor Petrino",
    weightclass: "Light Heavyweight",
    img: GUSKOV,
    wins: 10,
    losses: 0,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 92.99,
    reach_in_cm: 195.58,
    stance: "Orthodox",
    date_of_birth: "1997-08-28",
    significant_strikes_landed_per_minute: 3.07,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 2.65,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 4.15,
    takedown_accuracy: 70,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 1,
  },
  {
    id: 113,
    name: "Jon Jones",
    weightclass: "Heavyweight",
    nickname: "Bones",
    img: JONESJ,
    wins: 27,
    losses: 1,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 112.49,
    reach_in_cm: 213.36,
    stance: "Orthodox",
    date_of_birth: "1987-07-19",
    significant_strikes_landed_per_minute: 4.29,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 2.22,
    significant_strike_defence: 64,
    average_takedowns_landed_per_15_minutes: 1.93,
    takedown_accuracy: 45,
    takedown_defense: 95,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 114,
    name: "Tom Aspinall",
    weightclass: "Heavyweight",
    img: ASPINALL,
    wins: 14,
    losses: 3,
    draws: 0,
    height_cm: 195.58,
    weight_in_kg: 116.12,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1993-04-11",
    significant_strikes_landed_per_minute: 7.72,
    significant_striking_accuracy: 66,
    significant_strikes_absorbed_per_minute: 2.77,
    significant_strike_defence: 66,
    average_takedowns_landed_per_15_minutes: 3.46,
    takedown_accuracy: 100,
    takedown_defense: 100,
    average_submissions_attempted_per_15_minutes: 1.7,
  },
  {
    id: 115,
    name: "Ciryl Gane",
    weightclass: "Heavyweight",
    nickname: "Bon Gamin",
    img: GANE,
    wins: 12,
    losses: 2,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 111.13,
    reach_in_cm: 205.74,
    stance: "Orthodox",
    date_of_birth: "1990-04-12",
    significant_strikes_landed_per_minute: 5.49,
    significant_striking_accuracy: 60,
    significant_strikes_absorbed_per_minute: 2.19,
    significant_strike_defence: 63,
    average_takedowns_landed_per_15_minutes: 0.58,
    takedown_accuracy: 21,
    takedown_defense: 50,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 116,
    name: "Sergei Pavlovich",
    weightclass: "Heavyweight",
    img: SERGEI,
    wins: 18,
    losses: 2,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 116.57,
    reach_in_cm: 213.36,
    stance: "Southpaw",
    date_of_birth: "1992-05-13",
    significant_strikes_landed_per_minute: 8.21,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.61,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 117,
    name: "Stipe Miocic",
    weightclass: "Heavyweight",
    img: MIOCIC,
    wins: 20,
    losses: 4,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 108.86,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1982-08-19",
    significant_strikes_landed_per_minute: 4.82,
    significant_striking_accuracy: 53,
    significant_strikes_absorbed_per_minute: 3.82,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 1.86,
    takedown_accuracy: 34,
    takedown_defense: 68,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 118,
    name: "Curtis Blaydes",
    weightclass: "Heavyweight",
    nickname: "Razor",
    img: BLAYDES,
    wins: 17,
    losses: 4,
    draws: 0,
    height_cm: 193.04,
    weight_in_kg: 120.2,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1991-02-18",
    significant_strikes_landed_per_minute: 3.56,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 1.89,
    significant_strike_defence: 59,
    average_takedowns_landed_per_15_minutes: 5.93,
    takedown_accuracy: 53,
    takedown_defense: 33,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 119,
    name: "Alexander Volkov",
    weightclass: "Heavyweight",
    nickname: "Drago",
    img: VOLKOV,
    wins: 37,
    losses: 10,
    draws: 0,
    height_cm: 200.66,
    weight_in_kg: 113.4,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1988-10-24",
    significant_strikes_landed_per_minute: 5.1,
    significant_striking_accuracy: 57,
    significant_strikes_absorbed_per_minute: 3,
    significant_strike_defence: 54,
    average_takedowns_landed_per_15_minutes: 0.49,
    takedown_accuracy: 63,
    takedown_defense: 73,
    average_submissions_attempted_per_15_minutes: 0.2,
  },
  {
    id: 120,
    name: "Jailton Almeida",
    weightclass: "Heavyweight",
    nickname: "Malhadinho",
    img: ALMEIDA,
    wins: 20,
    losses: 2,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 92.99,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1991-06-26",
    significant_strikes_landed_per_minute: 2.78,
    significant_striking_accuracy: 64,
    significant_strikes_absorbed_per_minute: 0.52,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 5.14,
    takedown_accuracy: 55,
    takedown_defense: 75,
    average_submissions_attempted_per_15_minutes: 2.4,
  },
  {
    id: 121,
    name: "Serghei Spivac",
    weightclass: "Heavyweight",
    nickname: "Polar Bear",
    img: SPIVAC,
    wins: 16,
    losses: 4,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 117.93,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1995-01-24",
    significant_strikes_landed_per_minute: 3.54,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 3.79,
    significant_strike_defence: 49,
    average_takedowns_landed_per_15_minutes: 4.56,
    takedown_accuracy: 64,
    takedown_defense: 70,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 122,
    name: "Tai Tuivasa",
    weightclass: "Heavyweight",
    nickname: "Bam Bam",
    img: TAI,
    wins: 15,
    losses: 6,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 119.75,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1993-03-16",
    significant_strikes_landed_per_minute: 3.98,
    significant_striking_accuracy: 49,
    significant_strikes_absorbed_per_minute: 4.98,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 54,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 123,
    name: "Marcin Tybura",
    weightclass: "Heavyweight",
    nickname: "Tybur",
    img: TYBURA,
    wins: 24,
    losses: 8,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 112.94,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1985-11-09",
    significant_strikes_landed_per_minute: 3.55,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 3.35,
    significant_strike_defence: 55,
    average_takedowns_landed_per_15_minutes: 1.39,
    takedown_accuracy: 33,
    takedown_defense: 79,
    average_submissions_attempted_per_15_minutes: 0.1,
  },
  {
    id: 124,
    name: "Derrick Lewis",
    weightclass: "Heavyweight",
    nickname: "The Black Beast",
    img: LEWIS,
    wins: 27,
    losses: 12,
    draws: 0,
    height_cm: 190.5,
    weight_in_kg: 117.93,
    reach_in_cm: 200.66,
    stance: "Orthodox",
    date_of_birth: "1985-02-07",
    significant_strikes_landed_per_minute: 2.43,
    significant_striking_accuracy: 50,
    significant_strikes_absorbed_per_minute: 2.48,
    significant_strike_defence: 40,
    average_takedowns_landed_per_15_minutes: 0.53,
    takedown_accuracy: 26,
    takedown_defense: 53,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 125,
    name: "Jairzinho Rozenstruik",
    weightclass: "Heavyweight",
    nickname: "Bigi Boy",
    img: ROZENSTRUIK,
    wins: 13,
    losses: 5,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 109.77,
    reach_in_cm: 198.12,
    stance: "Orthodox",
    date_of_birth: "1988-03-17",
    significant_strikes_landed_per_minute: 2.81,
    significant_striking_accuracy: 45,
    significant_strikes_absorbed_per_minute: 3.15,
    significant_strike_defence: 45,
    average_takedowns_landed_per_15_minutes: 0,
    takedown_accuracy: 0,
    takedown_defense: 73,
    average_submissions_attempted_per_15_minutes: 0,
  },
  {
    id: 126,
    name: "Alexandr Romanov",
    weightclass: "Heavyweight",
    nickname: "King Kong",
    img: ROMANOV,
    wins: 17,
    losses: 2,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 118.84,
    reach_in_cm: 190.5,
    stance: "Southpaw",
    date_of_birth: "1990-12-11",
    significant_strikes_landed_per_minute: 4.06,
    significant_striking_accuracy: 52,
    significant_strikes_absorbed_per_minute: 2.2,
    significant_strike_defence: 50,
    average_takedowns_landed_per_15_minutes: 4.32,
    takedown_accuracy: 54,
    takedown_defense: 20,
    average_submissions_attempted_per_15_minutes: 0.9,
  },
  {
    id: 127,
    name: "Marcos Rogerio de Lima",
    weightclass: "Heavyweight",
    nickname: "Pezao",
    img: IMA,
    wins: 21,
    losses: 10,
    draws: 1,
    height_cm: 185.42,
    weight_in_kg: 114.76,
    reach_in_cm: 190.5,
    stance: "Orthodox",
    date_of_birth: "1985-06-25",
    significant_strikes_landed_per_minute: 3.61,
    significant_striking_accuracy: 56,
    significant_strikes_absorbed_per_minute: 2.96,
    significant_strike_defence: 51,
    average_takedowns_landed_per_15_minutes: 1.34,
    takedown_accuracy: 47,
    takedown_defense: 59,
    average_submissions_attempted_per_15_minutes: 0.5,
  },
  {
    id: 128,
    name: "Rodrigo Nascimento",
    weightclass: "Heavyweight",
    nickname: "Ze Colmeia",
    img: RODRIGO,
    wins: 11,
    losses: 1,
    draws: 0,
    height_cm: 187.96,
    weight_in_kg: 111.58,
    reach_in_cm: 203.2,
    stance: "Orthodox",
    date_of_birth: "1992-11-26",
    significant_strikes_landed_per_minute: 4.31,
    significant_striking_accuracy: 48,
    significant_strikes_absorbed_per_minute: 4.76,
    significant_strike_defence: 43,
    average_takedowns_landed_per_15_minutes: 1.2,
    takedown_accuracy: 33,
    takedown_defense: 77,
    average_submissions_attempted_per_15_minutes: 0.7,
  },
];
export default fighterStat;
