[
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Alexandre Pantoja",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Brandon Royval",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Brandon Moreno",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Amir Albazi",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Kai Kara-France",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Matheus Nicolau",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Manel Kape",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Muhammad Mokaev",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Alex Perez",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Tim Elliott",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Steve Erceg",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Matt Schnell",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Tagir Ulanbekov",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Tatsuro Taira",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "David Dvorak",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Flyweight",
    fighter: "Sumudaerji",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Sean O'Malley",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Merab Dvalishvili",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Aljamain Sterling",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Cory Sandhagen",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Petr Yan",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Marlon Vera",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Henry Cejudo",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Song Yadong",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Deiveson Figueiredo",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Rob Font",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Umar Nurmagomedov",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Jonathan Martinez",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Dominick Cruz",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Pedro Munhoz",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Mario Bautista",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Bantamweight",
    fighter: "Ricky Simon",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Ilia Topuria",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Alexander Volkanovski",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Max Holloway",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Brian Ortega",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Yair Rodriguez",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Movsar Evloev",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Arnold Allen",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Josh Emmett",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Calvin Kattar",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Giga Chikadze",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Bryce Mitchell",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Edson Barboza",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Dan Ige",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Sodiq Yusuff",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Lerone Murphy",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Featherweight",
    fighter: "Alex Caceres",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Islam Makhachev",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Charles Oliveira",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Justin Gaethje",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Dustin Poirier",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Arman Tsarukyan",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Michael Chandler",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Mateusz Gamrot",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Beneil Dariush",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Rafael Fiziev",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Jalin Turner",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Dan Hooker",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Rafael Dos Anjos",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Benoit Saint Denis",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Renato Moicano",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Bobby Green",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Lightweight",
    fighter: "Drew Dober",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Leon Edwards",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Kamaru Usman",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Belal Muhammad",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Shavkat Rakhmonov",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Gilbert Burns",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Colby Covington",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Ian Machado Garry",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Sean Brady",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Stephen Thompson",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Geoff Neal",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Vicente Luque",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Jack Della Maddalena",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Neil Magny",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Kevin Holland",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Michael Chiesa",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Welterweight",
    fighter: "Rinat Fakhretdinov",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Dricus Du Plessis",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Sean Strickland",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Israel Adesanya",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Robert Whittaker",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Jared Cannonier",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Marvin Vettori",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Brendan Allen",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Paulo Costa",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Nassourdine Imavov",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Roman Dolidze",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Jack Hermansson",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Khamzat Chimaev",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Paul Craig",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Anthony Hernandez",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Chris Curtis",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Middleweight",
    fighter: "Caio Borralho",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Alex Pereira",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Jamahal Hill",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Jiri Prochazka",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Magomed Ankalaev",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Jan Blachowicz",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Aleksandar Rakic",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Nikita Krylov",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Johnny Walker",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Khalil Rountree Jr.",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Volkan Oezdemir",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Anthony Smith",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Ryan Spann",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Alonzo Menifield",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Azamat Murzakanov",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Dominick Reyes",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Light Heavyweight",
    fighter: "Vitor Petrino",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Jon Jones",
    rank: 0,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Tom Aspinall",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Ciryl Gane",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Sergei Pavlovich",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Stipe Miocic",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Curtis Blaydes",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Alexander Volkov",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Jailton Almeida",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Serghei Spivac",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Tai Tuivasa",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Marcin Tybura",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Derrick Lewis",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Jairzinho Rozenstruik",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Alexandr Romanov",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Marcos Rogerio de Lima",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Heavyweight",
    fighter: "Rodrigo Nascimento",
    rank: 15,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Islam Makhachev",
    rank: 1,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Jon Jones",
    rank: 2,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Leon Edwards",
    rank: 3,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Alex Pereira",
    rank: 4,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Ilia Topuria",
    rank: 5,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Charles Oliveira",
    rank: 6,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Alexander Volkanovski",
    rank: 7,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Sean O'Malley",
    rank: 8,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Dricus Du Plessis",
    rank: 9,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Alexandre Pantoja",
    rank: 10,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Israel Adesanya",
    rank: 11,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Tom Aspinall",
    rank: 12,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Sean Strickland",
    rank: 13,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Max Holloway",
    rank: 14,
  },
  {
    date: "2024-03-05",
    weightclass: "Men's Pound-for-Pound",
    fighter: "Aljamain Sterling",
    rank: 15,
  },
];
